// Code generated by ent, DO NOT EDIT.

package partymaster

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the partymaster type in the database.
	Label = "party_master"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldLedgerID holds the string denoting the ledger_id field in the database.
	FieldLedgerID = "ledger_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldLegalName holds the string denoting the legal_name field in the database.
	FieldLegalName = "legal_name"
	// FieldGstNo holds the string denoting the gst_no field in the database.
	FieldGstNo = "gst_no"
	// FieldPanNo holds the string denoting the pan_no field in the database.
	FieldPanNo = "pan_no"
	// FieldContactPerson holds the string denoting the contact_person field in the database.
	FieldContactPerson = "contact_person"
	// FieldMobile holds the string denoting the mobile field in the database.
	FieldMobile = "mobile"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldWebsite holds the string denoting the website field in the database.
	FieldWebsite = "website"
	// FieldCreditLimit holds the string denoting the credit_limit field in the database.
	FieldCreditLimit = "credit_limit"
	// FieldCreditDays holds the string denoting the credit_days field in the database.
	FieldCreditDays = "credit_days"
	// FieldOpeningBalance holds the string denoting the opening_balance field in the database.
	FieldOpeningBalance = "opening_balance"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldPincode holds the string denoting the pincode field in the database.
	FieldPincode = "pincode"
	// EdgeLedger holds the string denoting the ledger edge name in mutations.
	EdgeLedger = "ledger"
	// Table holds the table name of the partymaster in the database.
	Table = "party_master"
	// LedgerTable is the table that holds the ledger relation/edge.
	LedgerTable = "party_master"
	// LedgerInverseTable is the table name for the Ledger entity.
	// It exists in this package in order to avoid circular dependency with the "ledger" package.
	LedgerInverseTable = "ledgers"
	// LedgerColumn is the table column denoting the ledger relation/edge.
	LedgerColumn = "ledger_id"
)

// Columns holds all SQL columns for partymaster fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldLedgerID,
	FieldType,
	FieldDisplayName,
	FieldLegalName,
	FieldGstNo,
	FieldPanNo,
	FieldContactPerson,
	FieldMobile,
	FieldPhone,
	FieldEmail,
	FieldWebsite,
	FieldCreditLimit,
	FieldCreditDays,
	FieldOpeningBalance,
	FieldAddress,
	FieldCity,
	FieldState,
	FieldCountry,
	FieldPincode,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DefaultCreditLimit holds the default value on creation for the "credit_limit" field.
	DefaultCreditLimit float64
	// DefaultCreditDays holds the default value on creation for the "credit_days" field.
	DefaultCreditDays int
	// DefaultOpeningBalance holds the default value on creation for the "opening_balance" field.
	DefaultOpeningBalance float64
	// DefaultCountry holds the default value on creation for the "country" field.
	DefaultCountry string
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeCUSTOMER Type = "CUSTOMER"
	TypeSUPPLIER Type = "SUPPLIER"
	TypeBOTH     Type = "BOTH"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeCUSTOMER, TypeSUPPLIER, TypeBOTH:
		return nil
	default:
		return fmt.Errorf("partymaster: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the PartyMaster queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByLedgerID orders the results by the ledger_id field.
func ByLedgerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLedgerID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByLegalName orders the results by the legal_name field.
func ByLegalName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLegalName, opts...).ToFunc()
}

// ByGstNo orders the results by the gst_no field.
func ByGstNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGstNo, opts...).ToFunc()
}

// ByPanNo orders the results by the pan_no field.
func ByPanNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPanNo, opts...).ToFunc()
}

// ByContactPerson orders the results by the contact_person field.
func ByContactPerson(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactPerson, opts...).ToFunc()
}

// ByMobile orders the results by the mobile field.
func ByMobile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMobile, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByWebsite orders the results by the website field.
func ByWebsite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebsite, opts...).ToFunc()
}

// ByCreditLimit orders the results by the credit_limit field.
func ByCreditLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditLimit, opts...).ToFunc()
}

// ByCreditDays orders the results by the credit_days field.
func ByCreditDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditDays, opts...).ToFunc()
}

// ByOpeningBalance orders the results by the opening_balance field.
func ByOpeningBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpeningBalance, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByCity orders the results by the city field.
func ByCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCity, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByPincode orders the results by the pincode field.
func ByPincode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPincode, opts...).ToFunc()
}

// ByLedgerField orders the results by ledger field.
func ByLedgerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLedgerStep(), sql.OrderByField(field, opts...))
	}
}
func newLedgerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LedgerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, LedgerTable, LedgerColumn),
	)
}
