// Code generated by ent, DO NOT EDIT.

package partymaster

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/subhasundardass/retui/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldUpdateTime, v))
}

// LedgerID applies equality check predicate on the "ledger_id" field. It's identical to LedgerIDEQ.
func LedgerID(v int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldLedgerID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldDisplayName, v))
}

// LegalName applies equality check predicate on the "legal_name" field. It's identical to LegalNameEQ.
func LegalName(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldLegalName, v))
}

// GstNo applies equality check predicate on the "gst_no" field. It's identical to GstNoEQ.
func GstNo(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldGstNo, v))
}

// PanNo applies equality check predicate on the "pan_no" field. It's identical to PanNoEQ.
func PanNo(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldPanNo, v))
}

// ContactPerson applies equality check predicate on the "contact_person" field. It's identical to ContactPersonEQ.
func ContactPerson(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldContactPerson, v))
}

// Mobile applies equality check predicate on the "mobile" field. It's identical to MobileEQ.
func Mobile(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldMobile, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldPhone, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldEmail, v))
}

// Website applies equality check predicate on the "website" field. It's identical to WebsiteEQ.
func Website(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldWebsite, v))
}

// CreditLimit applies equality check predicate on the "credit_limit" field. It's identical to CreditLimitEQ.
func CreditLimit(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldCreditLimit, v))
}

// CreditDays applies equality check predicate on the "credit_days" field. It's identical to CreditDaysEQ.
func CreditDays(v int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldCreditDays, v))
}

// OpeningBalance applies equality check predicate on the "opening_balance" field. It's identical to OpeningBalanceEQ.
func OpeningBalance(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldOpeningBalance, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldAddress, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldCity, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldState, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldCountry, v))
}

// Pincode applies equality check predicate on the "pincode" field. It's identical to PincodeEQ.
func Pincode(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldPincode, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldUpdateTime, v))
}

// LedgerIDEQ applies the EQ predicate on the "ledger_id" field.
func LedgerIDEQ(v int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldLedgerID, v))
}

// LedgerIDNEQ applies the NEQ predicate on the "ledger_id" field.
func LedgerIDNEQ(v int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldLedgerID, v))
}

// LedgerIDIn applies the In predicate on the "ledger_id" field.
func LedgerIDIn(vs ...int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldLedgerID, vs...))
}

// LedgerIDNotIn applies the NotIn predicate on the "ledger_id" field.
func LedgerIDNotIn(vs ...int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldLedgerID, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldType, vs...))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldDisplayName, v))
}

// LegalNameEQ applies the EQ predicate on the "legal_name" field.
func LegalNameEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldLegalName, v))
}

// LegalNameNEQ applies the NEQ predicate on the "legal_name" field.
func LegalNameNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldLegalName, v))
}

// LegalNameIn applies the In predicate on the "legal_name" field.
func LegalNameIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldLegalName, vs...))
}

// LegalNameNotIn applies the NotIn predicate on the "legal_name" field.
func LegalNameNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldLegalName, vs...))
}

// LegalNameGT applies the GT predicate on the "legal_name" field.
func LegalNameGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldLegalName, v))
}

// LegalNameGTE applies the GTE predicate on the "legal_name" field.
func LegalNameGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldLegalName, v))
}

// LegalNameLT applies the LT predicate on the "legal_name" field.
func LegalNameLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldLegalName, v))
}

// LegalNameLTE applies the LTE predicate on the "legal_name" field.
func LegalNameLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldLegalName, v))
}

// LegalNameContains applies the Contains predicate on the "legal_name" field.
func LegalNameContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldLegalName, v))
}

// LegalNameHasPrefix applies the HasPrefix predicate on the "legal_name" field.
func LegalNameHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldLegalName, v))
}

// LegalNameHasSuffix applies the HasSuffix predicate on the "legal_name" field.
func LegalNameHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldLegalName, v))
}

// LegalNameIsNil applies the IsNil predicate on the "legal_name" field.
func LegalNameIsNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIsNull(FieldLegalName))
}

// LegalNameNotNil applies the NotNil predicate on the "legal_name" field.
func LegalNameNotNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotNull(FieldLegalName))
}

// LegalNameEqualFold applies the EqualFold predicate on the "legal_name" field.
func LegalNameEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldLegalName, v))
}

// LegalNameContainsFold applies the ContainsFold predicate on the "legal_name" field.
func LegalNameContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldLegalName, v))
}

// GstNoEQ applies the EQ predicate on the "gst_no" field.
func GstNoEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldGstNo, v))
}

// GstNoNEQ applies the NEQ predicate on the "gst_no" field.
func GstNoNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldGstNo, v))
}

// GstNoIn applies the In predicate on the "gst_no" field.
func GstNoIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldGstNo, vs...))
}

// GstNoNotIn applies the NotIn predicate on the "gst_no" field.
func GstNoNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldGstNo, vs...))
}

// GstNoGT applies the GT predicate on the "gst_no" field.
func GstNoGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldGstNo, v))
}

// GstNoGTE applies the GTE predicate on the "gst_no" field.
func GstNoGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldGstNo, v))
}

// GstNoLT applies the LT predicate on the "gst_no" field.
func GstNoLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldGstNo, v))
}

// GstNoLTE applies the LTE predicate on the "gst_no" field.
func GstNoLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldGstNo, v))
}

// GstNoContains applies the Contains predicate on the "gst_no" field.
func GstNoContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldGstNo, v))
}

// GstNoHasPrefix applies the HasPrefix predicate on the "gst_no" field.
func GstNoHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldGstNo, v))
}

// GstNoHasSuffix applies the HasSuffix predicate on the "gst_no" field.
func GstNoHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldGstNo, v))
}

// GstNoIsNil applies the IsNil predicate on the "gst_no" field.
func GstNoIsNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIsNull(FieldGstNo))
}

// GstNoNotNil applies the NotNil predicate on the "gst_no" field.
func GstNoNotNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotNull(FieldGstNo))
}

// GstNoEqualFold applies the EqualFold predicate on the "gst_no" field.
func GstNoEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldGstNo, v))
}

// GstNoContainsFold applies the ContainsFold predicate on the "gst_no" field.
func GstNoContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldGstNo, v))
}

// PanNoEQ applies the EQ predicate on the "pan_no" field.
func PanNoEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldPanNo, v))
}

// PanNoNEQ applies the NEQ predicate on the "pan_no" field.
func PanNoNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldPanNo, v))
}

// PanNoIn applies the In predicate on the "pan_no" field.
func PanNoIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldPanNo, vs...))
}

// PanNoNotIn applies the NotIn predicate on the "pan_no" field.
func PanNoNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldPanNo, vs...))
}

// PanNoGT applies the GT predicate on the "pan_no" field.
func PanNoGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldPanNo, v))
}

// PanNoGTE applies the GTE predicate on the "pan_no" field.
func PanNoGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldPanNo, v))
}

// PanNoLT applies the LT predicate on the "pan_no" field.
func PanNoLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldPanNo, v))
}

// PanNoLTE applies the LTE predicate on the "pan_no" field.
func PanNoLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldPanNo, v))
}

// PanNoContains applies the Contains predicate on the "pan_no" field.
func PanNoContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldPanNo, v))
}

// PanNoHasPrefix applies the HasPrefix predicate on the "pan_no" field.
func PanNoHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldPanNo, v))
}

// PanNoHasSuffix applies the HasSuffix predicate on the "pan_no" field.
func PanNoHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldPanNo, v))
}

// PanNoIsNil applies the IsNil predicate on the "pan_no" field.
func PanNoIsNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIsNull(FieldPanNo))
}

// PanNoNotNil applies the NotNil predicate on the "pan_no" field.
func PanNoNotNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotNull(FieldPanNo))
}

// PanNoEqualFold applies the EqualFold predicate on the "pan_no" field.
func PanNoEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldPanNo, v))
}

// PanNoContainsFold applies the ContainsFold predicate on the "pan_no" field.
func PanNoContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldPanNo, v))
}

// ContactPersonEQ applies the EQ predicate on the "contact_person" field.
func ContactPersonEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldContactPerson, v))
}

// ContactPersonNEQ applies the NEQ predicate on the "contact_person" field.
func ContactPersonNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldContactPerson, v))
}

// ContactPersonIn applies the In predicate on the "contact_person" field.
func ContactPersonIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldContactPerson, vs...))
}

// ContactPersonNotIn applies the NotIn predicate on the "contact_person" field.
func ContactPersonNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldContactPerson, vs...))
}

// ContactPersonGT applies the GT predicate on the "contact_person" field.
func ContactPersonGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldContactPerson, v))
}

// ContactPersonGTE applies the GTE predicate on the "contact_person" field.
func ContactPersonGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldContactPerson, v))
}

// ContactPersonLT applies the LT predicate on the "contact_person" field.
func ContactPersonLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldContactPerson, v))
}

// ContactPersonLTE applies the LTE predicate on the "contact_person" field.
func ContactPersonLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldContactPerson, v))
}

// ContactPersonContains applies the Contains predicate on the "contact_person" field.
func ContactPersonContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldContactPerson, v))
}

// ContactPersonHasPrefix applies the HasPrefix predicate on the "contact_person" field.
func ContactPersonHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldContactPerson, v))
}

// ContactPersonHasSuffix applies the HasSuffix predicate on the "contact_person" field.
func ContactPersonHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldContactPerson, v))
}

// ContactPersonIsNil applies the IsNil predicate on the "contact_person" field.
func ContactPersonIsNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIsNull(FieldContactPerson))
}

// ContactPersonNotNil applies the NotNil predicate on the "contact_person" field.
func ContactPersonNotNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotNull(FieldContactPerson))
}

// ContactPersonEqualFold applies the EqualFold predicate on the "contact_person" field.
func ContactPersonEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldContactPerson, v))
}

// ContactPersonContainsFold applies the ContainsFold predicate on the "contact_person" field.
func ContactPersonContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldContactPerson, v))
}

// MobileEQ applies the EQ predicate on the "mobile" field.
func MobileEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldMobile, v))
}

// MobileNEQ applies the NEQ predicate on the "mobile" field.
func MobileNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldMobile, v))
}

// MobileIn applies the In predicate on the "mobile" field.
func MobileIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldMobile, vs...))
}

// MobileNotIn applies the NotIn predicate on the "mobile" field.
func MobileNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldMobile, vs...))
}

// MobileGT applies the GT predicate on the "mobile" field.
func MobileGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldMobile, v))
}

// MobileGTE applies the GTE predicate on the "mobile" field.
func MobileGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldMobile, v))
}

// MobileLT applies the LT predicate on the "mobile" field.
func MobileLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldMobile, v))
}

// MobileLTE applies the LTE predicate on the "mobile" field.
func MobileLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldMobile, v))
}

// MobileContains applies the Contains predicate on the "mobile" field.
func MobileContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldMobile, v))
}

// MobileHasPrefix applies the HasPrefix predicate on the "mobile" field.
func MobileHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldMobile, v))
}

// MobileHasSuffix applies the HasSuffix predicate on the "mobile" field.
func MobileHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldMobile, v))
}

// MobileIsNil applies the IsNil predicate on the "mobile" field.
func MobileIsNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIsNull(FieldMobile))
}

// MobileNotNil applies the NotNil predicate on the "mobile" field.
func MobileNotNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotNull(FieldMobile))
}

// MobileEqualFold applies the EqualFold predicate on the "mobile" field.
func MobileEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldMobile, v))
}

// MobileContainsFold applies the ContainsFold predicate on the "mobile" field.
func MobileContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldMobile, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldPhone, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldEmail, v))
}

// WebsiteEQ applies the EQ predicate on the "website" field.
func WebsiteEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldWebsite, v))
}

// WebsiteNEQ applies the NEQ predicate on the "website" field.
func WebsiteNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldWebsite, v))
}

// WebsiteIn applies the In predicate on the "website" field.
func WebsiteIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldWebsite, vs...))
}

// WebsiteNotIn applies the NotIn predicate on the "website" field.
func WebsiteNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldWebsite, vs...))
}

// WebsiteGT applies the GT predicate on the "website" field.
func WebsiteGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldWebsite, v))
}

// WebsiteGTE applies the GTE predicate on the "website" field.
func WebsiteGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldWebsite, v))
}

// WebsiteLT applies the LT predicate on the "website" field.
func WebsiteLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldWebsite, v))
}

// WebsiteLTE applies the LTE predicate on the "website" field.
func WebsiteLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldWebsite, v))
}

// WebsiteContains applies the Contains predicate on the "website" field.
func WebsiteContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldWebsite, v))
}

// WebsiteHasPrefix applies the HasPrefix predicate on the "website" field.
func WebsiteHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldWebsite, v))
}

// WebsiteHasSuffix applies the HasSuffix predicate on the "website" field.
func WebsiteHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldWebsite, v))
}

// WebsiteIsNil applies the IsNil predicate on the "website" field.
func WebsiteIsNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIsNull(FieldWebsite))
}

// WebsiteNotNil applies the NotNil predicate on the "website" field.
func WebsiteNotNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotNull(FieldWebsite))
}

// WebsiteEqualFold applies the EqualFold predicate on the "website" field.
func WebsiteEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldWebsite, v))
}

// WebsiteContainsFold applies the ContainsFold predicate on the "website" field.
func WebsiteContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldWebsite, v))
}

// CreditLimitEQ applies the EQ predicate on the "credit_limit" field.
func CreditLimitEQ(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldCreditLimit, v))
}

// CreditLimitNEQ applies the NEQ predicate on the "credit_limit" field.
func CreditLimitNEQ(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldCreditLimit, v))
}

// CreditLimitIn applies the In predicate on the "credit_limit" field.
func CreditLimitIn(vs ...float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldCreditLimit, vs...))
}

// CreditLimitNotIn applies the NotIn predicate on the "credit_limit" field.
func CreditLimitNotIn(vs ...float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldCreditLimit, vs...))
}

// CreditLimitGT applies the GT predicate on the "credit_limit" field.
func CreditLimitGT(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldCreditLimit, v))
}

// CreditLimitGTE applies the GTE predicate on the "credit_limit" field.
func CreditLimitGTE(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldCreditLimit, v))
}

// CreditLimitLT applies the LT predicate on the "credit_limit" field.
func CreditLimitLT(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldCreditLimit, v))
}

// CreditLimitLTE applies the LTE predicate on the "credit_limit" field.
func CreditLimitLTE(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldCreditLimit, v))
}

// CreditDaysEQ applies the EQ predicate on the "credit_days" field.
func CreditDaysEQ(v int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldCreditDays, v))
}

// CreditDaysNEQ applies the NEQ predicate on the "credit_days" field.
func CreditDaysNEQ(v int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldCreditDays, v))
}

// CreditDaysIn applies the In predicate on the "credit_days" field.
func CreditDaysIn(vs ...int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldCreditDays, vs...))
}

// CreditDaysNotIn applies the NotIn predicate on the "credit_days" field.
func CreditDaysNotIn(vs ...int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldCreditDays, vs...))
}

// CreditDaysGT applies the GT predicate on the "credit_days" field.
func CreditDaysGT(v int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldCreditDays, v))
}

// CreditDaysGTE applies the GTE predicate on the "credit_days" field.
func CreditDaysGTE(v int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldCreditDays, v))
}

// CreditDaysLT applies the LT predicate on the "credit_days" field.
func CreditDaysLT(v int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldCreditDays, v))
}

// CreditDaysLTE applies the LTE predicate on the "credit_days" field.
func CreditDaysLTE(v int) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldCreditDays, v))
}

// OpeningBalanceEQ applies the EQ predicate on the "opening_balance" field.
func OpeningBalanceEQ(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldOpeningBalance, v))
}

// OpeningBalanceNEQ applies the NEQ predicate on the "opening_balance" field.
func OpeningBalanceNEQ(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldOpeningBalance, v))
}

// OpeningBalanceIn applies the In predicate on the "opening_balance" field.
func OpeningBalanceIn(vs ...float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldOpeningBalance, vs...))
}

// OpeningBalanceNotIn applies the NotIn predicate on the "opening_balance" field.
func OpeningBalanceNotIn(vs ...float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldOpeningBalance, vs...))
}

// OpeningBalanceGT applies the GT predicate on the "opening_balance" field.
func OpeningBalanceGT(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldOpeningBalance, v))
}

// OpeningBalanceGTE applies the GTE predicate on the "opening_balance" field.
func OpeningBalanceGTE(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldOpeningBalance, v))
}

// OpeningBalanceLT applies the LT predicate on the "opening_balance" field.
func OpeningBalanceLT(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldOpeningBalance, v))
}

// OpeningBalanceLTE applies the LTE predicate on the "opening_balance" field.
func OpeningBalanceLTE(v float64) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldOpeningBalance, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressIsNil applies the IsNil predicate on the "address" field.
func AddressIsNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIsNull(FieldAddress))
}

// AddressNotNil applies the NotNil predicate on the "address" field.
func AddressNotNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotNull(FieldAddress))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldAddress, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldCity, v))
}

// CityIsNil applies the IsNil predicate on the "city" field.
func CityIsNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIsNull(FieldCity))
}

// CityNotNil applies the NotNil predicate on the "city" field.
func CityNotNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotNull(FieldCity))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldCity, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldState, v))
}

// StateIsNil applies the IsNil predicate on the "state" field.
func StateIsNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIsNull(FieldState))
}

// StateNotNil applies the NotNil predicate on the "state" field.
func StateNotNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotNull(FieldState))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldState, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldCountry, v))
}

// PincodeEQ applies the EQ predicate on the "pincode" field.
func PincodeEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEQ(FieldPincode, v))
}

// PincodeNEQ applies the NEQ predicate on the "pincode" field.
func PincodeNEQ(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNEQ(FieldPincode, v))
}

// PincodeIn applies the In predicate on the "pincode" field.
func PincodeIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIn(FieldPincode, vs...))
}

// PincodeNotIn applies the NotIn predicate on the "pincode" field.
func PincodeNotIn(vs ...string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotIn(FieldPincode, vs...))
}

// PincodeGT applies the GT predicate on the "pincode" field.
func PincodeGT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGT(FieldPincode, v))
}

// PincodeGTE applies the GTE predicate on the "pincode" field.
func PincodeGTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldGTE(FieldPincode, v))
}

// PincodeLT applies the LT predicate on the "pincode" field.
func PincodeLT(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLT(FieldPincode, v))
}

// PincodeLTE applies the LTE predicate on the "pincode" field.
func PincodeLTE(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldLTE(FieldPincode, v))
}

// PincodeContains applies the Contains predicate on the "pincode" field.
func PincodeContains(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContains(FieldPincode, v))
}

// PincodeHasPrefix applies the HasPrefix predicate on the "pincode" field.
func PincodeHasPrefix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasPrefix(FieldPincode, v))
}

// PincodeHasSuffix applies the HasSuffix predicate on the "pincode" field.
func PincodeHasSuffix(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldHasSuffix(FieldPincode, v))
}

// PincodeIsNil applies the IsNil predicate on the "pincode" field.
func PincodeIsNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldIsNull(FieldPincode))
}

// PincodeNotNil applies the NotNil predicate on the "pincode" field.
func PincodeNotNil() predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldNotNull(FieldPincode))
}

// PincodeEqualFold applies the EqualFold predicate on the "pincode" field.
func PincodeEqualFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldEqualFold(FieldPincode, v))
}

// PincodeContainsFold applies the ContainsFold predicate on the "pincode" field.
func PincodeContainsFold(v string) predicate.PartyMaster {
	return predicate.PartyMaster(sql.FieldContainsFold(FieldPincode, v))
}

// HasLedger applies the HasEdge predicate on the "ledger" edge.
func HasLedger() predicate.PartyMaster {
	return predicate.PartyMaster(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, LedgerTable, LedgerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerWith applies the HasEdge predicate on the "ledger" edge with a given conditions (other predicates).
func HasLedgerWith(preds ...predicate.Ledger) predicate.PartyMaster {
	return predicate.PartyMaster(func(s *sql.Selector) {
		step := newLedgerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PartyMaster) predicate.PartyMaster {
	return predicate.PartyMaster(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PartyMaster) predicate.PartyMaster {
	return predicate.PartyMaster(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PartyMaster) predicate.PartyMaster {
	return predicate.PartyMaster(sql.NotPredicates(p))
}
