// Code generated by ent, DO NOT EDIT.

package company

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/subhasundardass/retui/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldName, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCode, v))
}

// LegalName applies equality check predicate on the "legal_name" field. It's identical to LegalNameEQ.
func LegalName(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldLegalName, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldEmail, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldPhone, v))
}

// Website applies equality check predicate on the "website" field. It's identical to WebsiteEQ.
func Website(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldWebsite, v))
}

// TaxID applies equality check predicate on the "tax_id" field. It's identical to TaxIDEQ.
func TaxID(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldTaxID, v))
}

// Gstin applies equality check predicate on the "gstin" field. It's identical to GstinEQ.
func Gstin(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldGstin, v))
}

// Pan applies equality check predicate on the "pan" field. It's identical to PanEQ.
func Pan(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldPan, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCurrency, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldTimezone, v))
}

// Logo applies equality check predicate on the "logo" field. It's identical to LogoEQ.
func Logo(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldLogo, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldAddress, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCity, v))
}

// PostalCode applies equality check predicate on the "postal_code" field. It's identical to PostalCodeEQ.
func PostalCode(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldPostalCode, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldName, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldCode, v))
}

// LegalNameEQ applies the EQ predicate on the "legal_name" field.
func LegalNameEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldLegalName, v))
}

// LegalNameNEQ applies the NEQ predicate on the "legal_name" field.
func LegalNameNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldLegalName, v))
}

// LegalNameIn applies the In predicate on the "legal_name" field.
func LegalNameIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldLegalName, vs...))
}

// LegalNameNotIn applies the NotIn predicate on the "legal_name" field.
func LegalNameNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldLegalName, vs...))
}

// LegalNameGT applies the GT predicate on the "legal_name" field.
func LegalNameGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldLegalName, v))
}

// LegalNameGTE applies the GTE predicate on the "legal_name" field.
func LegalNameGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldLegalName, v))
}

// LegalNameLT applies the LT predicate on the "legal_name" field.
func LegalNameLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldLegalName, v))
}

// LegalNameLTE applies the LTE predicate on the "legal_name" field.
func LegalNameLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldLegalName, v))
}

// LegalNameContains applies the Contains predicate on the "legal_name" field.
func LegalNameContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldLegalName, v))
}

// LegalNameHasPrefix applies the HasPrefix predicate on the "legal_name" field.
func LegalNameHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldLegalName, v))
}

// LegalNameHasSuffix applies the HasSuffix predicate on the "legal_name" field.
func LegalNameHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldLegalName, v))
}

// LegalNameIsNil applies the IsNil predicate on the "legal_name" field.
func LegalNameIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldLegalName))
}

// LegalNameNotNil applies the NotNil predicate on the "legal_name" field.
func LegalNameNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldLegalName))
}

// LegalNameEqualFold applies the EqualFold predicate on the "legal_name" field.
func LegalNameEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldLegalName, v))
}

// LegalNameContainsFold applies the ContainsFold predicate on the "legal_name" field.
func LegalNameContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldLegalName, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldEmail, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldPhone, v))
}

// WebsiteEQ applies the EQ predicate on the "website" field.
func WebsiteEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldWebsite, v))
}

// WebsiteNEQ applies the NEQ predicate on the "website" field.
func WebsiteNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldWebsite, v))
}

// WebsiteIn applies the In predicate on the "website" field.
func WebsiteIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldWebsite, vs...))
}

// WebsiteNotIn applies the NotIn predicate on the "website" field.
func WebsiteNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldWebsite, vs...))
}

// WebsiteGT applies the GT predicate on the "website" field.
func WebsiteGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldWebsite, v))
}

// WebsiteGTE applies the GTE predicate on the "website" field.
func WebsiteGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldWebsite, v))
}

// WebsiteLT applies the LT predicate on the "website" field.
func WebsiteLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldWebsite, v))
}

// WebsiteLTE applies the LTE predicate on the "website" field.
func WebsiteLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldWebsite, v))
}

// WebsiteContains applies the Contains predicate on the "website" field.
func WebsiteContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldWebsite, v))
}

// WebsiteHasPrefix applies the HasPrefix predicate on the "website" field.
func WebsiteHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldWebsite, v))
}

// WebsiteHasSuffix applies the HasSuffix predicate on the "website" field.
func WebsiteHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldWebsite, v))
}

// WebsiteIsNil applies the IsNil predicate on the "website" field.
func WebsiteIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldWebsite))
}

// WebsiteNotNil applies the NotNil predicate on the "website" field.
func WebsiteNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldWebsite))
}

// WebsiteEqualFold applies the EqualFold predicate on the "website" field.
func WebsiteEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldWebsite, v))
}

// WebsiteContainsFold applies the ContainsFold predicate on the "website" field.
func WebsiteContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldWebsite, v))
}

// TaxIDEQ applies the EQ predicate on the "tax_id" field.
func TaxIDEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldTaxID, v))
}

// TaxIDNEQ applies the NEQ predicate on the "tax_id" field.
func TaxIDNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldTaxID, v))
}

// TaxIDIn applies the In predicate on the "tax_id" field.
func TaxIDIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldTaxID, vs...))
}

// TaxIDNotIn applies the NotIn predicate on the "tax_id" field.
func TaxIDNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldTaxID, vs...))
}

// TaxIDGT applies the GT predicate on the "tax_id" field.
func TaxIDGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldTaxID, v))
}

// TaxIDGTE applies the GTE predicate on the "tax_id" field.
func TaxIDGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldTaxID, v))
}

// TaxIDLT applies the LT predicate on the "tax_id" field.
func TaxIDLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldTaxID, v))
}

// TaxIDLTE applies the LTE predicate on the "tax_id" field.
func TaxIDLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldTaxID, v))
}

// TaxIDContains applies the Contains predicate on the "tax_id" field.
func TaxIDContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldTaxID, v))
}

// TaxIDHasPrefix applies the HasPrefix predicate on the "tax_id" field.
func TaxIDHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldTaxID, v))
}

// TaxIDHasSuffix applies the HasSuffix predicate on the "tax_id" field.
func TaxIDHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldTaxID, v))
}

// TaxIDIsNil applies the IsNil predicate on the "tax_id" field.
func TaxIDIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldTaxID))
}

// TaxIDNotNil applies the NotNil predicate on the "tax_id" field.
func TaxIDNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldTaxID))
}

// TaxIDEqualFold applies the EqualFold predicate on the "tax_id" field.
func TaxIDEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldTaxID, v))
}

// TaxIDContainsFold applies the ContainsFold predicate on the "tax_id" field.
func TaxIDContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldTaxID, v))
}

// GstinEQ applies the EQ predicate on the "gstin" field.
func GstinEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldGstin, v))
}

// GstinNEQ applies the NEQ predicate on the "gstin" field.
func GstinNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldGstin, v))
}

// GstinIn applies the In predicate on the "gstin" field.
func GstinIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldGstin, vs...))
}

// GstinNotIn applies the NotIn predicate on the "gstin" field.
func GstinNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldGstin, vs...))
}

// GstinGT applies the GT predicate on the "gstin" field.
func GstinGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldGstin, v))
}

// GstinGTE applies the GTE predicate on the "gstin" field.
func GstinGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldGstin, v))
}

// GstinLT applies the LT predicate on the "gstin" field.
func GstinLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldGstin, v))
}

// GstinLTE applies the LTE predicate on the "gstin" field.
func GstinLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldGstin, v))
}

// GstinContains applies the Contains predicate on the "gstin" field.
func GstinContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldGstin, v))
}

// GstinHasPrefix applies the HasPrefix predicate on the "gstin" field.
func GstinHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldGstin, v))
}

// GstinHasSuffix applies the HasSuffix predicate on the "gstin" field.
func GstinHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldGstin, v))
}

// GstinIsNil applies the IsNil predicate on the "gstin" field.
func GstinIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldGstin))
}

// GstinNotNil applies the NotNil predicate on the "gstin" field.
func GstinNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldGstin))
}

// GstinEqualFold applies the EqualFold predicate on the "gstin" field.
func GstinEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldGstin, v))
}

// GstinContainsFold applies the ContainsFold predicate on the "gstin" field.
func GstinContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldGstin, v))
}

// PanEQ applies the EQ predicate on the "pan" field.
func PanEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldPan, v))
}

// PanNEQ applies the NEQ predicate on the "pan" field.
func PanNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldPan, v))
}

// PanIn applies the In predicate on the "pan" field.
func PanIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldPan, vs...))
}

// PanNotIn applies the NotIn predicate on the "pan" field.
func PanNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldPan, vs...))
}

// PanGT applies the GT predicate on the "pan" field.
func PanGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldPan, v))
}

// PanGTE applies the GTE predicate on the "pan" field.
func PanGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldPan, v))
}

// PanLT applies the LT predicate on the "pan" field.
func PanLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldPan, v))
}

// PanLTE applies the LTE predicate on the "pan" field.
func PanLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldPan, v))
}

// PanContains applies the Contains predicate on the "pan" field.
func PanContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldPan, v))
}

// PanHasPrefix applies the HasPrefix predicate on the "pan" field.
func PanHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldPan, v))
}

// PanHasSuffix applies the HasSuffix predicate on the "pan" field.
func PanHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldPan, v))
}

// PanIsNil applies the IsNil predicate on the "pan" field.
func PanIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldPan))
}

// PanNotNil applies the NotNil predicate on the "pan" field.
func PanNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldPan))
}

// PanEqualFold applies the EqualFold predicate on the "pan" field.
func PanEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldPan, v))
}

// PanContainsFold applies the ContainsFold predicate on the "pan" field.
func PanContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldPan, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldCurrency, v))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldTimezone, v))
}

// LogoEQ applies the EQ predicate on the "logo" field.
func LogoEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldLogo, v))
}

// LogoNEQ applies the NEQ predicate on the "logo" field.
func LogoNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldLogo, v))
}

// LogoIn applies the In predicate on the "logo" field.
func LogoIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldLogo, vs...))
}

// LogoNotIn applies the NotIn predicate on the "logo" field.
func LogoNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldLogo, vs...))
}

// LogoGT applies the GT predicate on the "logo" field.
func LogoGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldLogo, v))
}

// LogoGTE applies the GTE predicate on the "logo" field.
func LogoGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldLogo, v))
}

// LogoLT applies the LT predicate on the "logo" field.
func LogoLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldLogo, v))
}

// LogoLTE applies the LTE predicate on the "logo" field.
func LogoLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldLogo, v))
}

// LogoContains applies the Contains predicate on the "logo" field.
func LogoContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldLogo, v))
}

// LogoHasPrefix applies the HasPrefix predicate on the "logo" field.
func LogoHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldLogo, v))
}

// LogoHasSuffix applies the HasSuffix predicate on the "logo" field.
func LogoHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldLogo, v))
}

// LogoIsNil applies the IsNil predicate on the "logo" field.
func LogoIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldLogo))
}

// LogoNotNil applies the NotNil predicate on the "logo" field.
func LogoNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldLogo))
}

// LogoEqualFold applies the EqualFold predicate on the "logo" field.
func LogoEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldLogo, v))
}

// LogoContainsFold applies the ContainsFold predicate on the "logo" field.
func LogoContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldLogo, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressIsNil applies the IsNil predicate on the "address" field.
func AddressIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldAddress))
}

// AddressNotNil applies the NotNil predicate on the "address" field.
func AddressNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldAddress))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldAddress, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldCity, v))
}

// CityIsNil applies the IsNil predicate on the "city" field.
func CityIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldCity))
}

// CityNotNil applies the NotNil predicate on the "city" field.
func CityNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldCity))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldCity, v))
}

// PostalCodeEQ applies the EQ predicate on the "postal_code" field.
func PostalCodeEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldPostalCode, v))
}

// PostalCodeNEQ applies the NEQ predicate on the "postal_code" field.
func PostalCodeNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldPostalCode, v))
}

// PostalCodeIn applies the In predicate on the "postal_code" field.
func PostalCodeIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldPostalCode, vs...))
}

// PostalCodeNotIn applies the NotIn predicate on the "postal_code" field.
func PostalCodeNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldPostalCode, vs...))
}

// PostalCodeGT applies the GT predicate on the "postal_code" field.
func PostalCodeGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldPostalCode, v))
}

// PostalCodeGTE applies the GTE predicate on the "postal_code" field.
func PostalCodeGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldPostalCode, v))
}

// PostalCodeLT applies the LT predicate on the "postal_code" field.
func PostalCodeLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldPostalCode, v))
}

// PostalCodeLTE applies the LTE predicate on the "postal_code" field.
func PostalCodeLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldPostalCode, v))
}

// PostalCodeContains applies the Contains predicate on the "postal_code" field.
func PostalCodeContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldPostalCode, v))
}

// PostalCodeHasPrefix applies the HasPrefix predicate on the "postal_code" field.
func PostalCodeHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldPostalCode, v))
}

// PostalCodeHasSuffix applies the HasSuffix predicate on the "postal_code" field.
func PostalCodeHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldPostalCode, v))
}

// PostalCodeIsNil applies the IsNil predicate on the "postal_code" field.
func PostalCodeIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldPostalCode))
}

// PostalCodeNotNil applies the NotNil predicate on the "postal_code" field.
func PostalCodeNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldPostalCode))
}

// PostalCodeEqualFold applies the EqualFold predicate on the "postal_code" field.
func PostalCodeEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldPostalCode, v))
}

// PostalCodeContainsFold applies the ContainsFold predicate on the "postal_code" field.
func PostalCodeContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldPostalCode, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCountryRef applies the HasEdge predicate on the "country_ref" edge.
func HasCountryRef() predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CountryRefTable, CountryRefColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCountryRefWith applies the HasEdge predicate on the "country_ref" edge with a given conditions (other predicates).
func HasCountryRefWith(preds ...predicate.Country) predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := newCountryRefStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStateRef applies the HasEdge predicate on the "state_ref" edge.
func HasStateRef() predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, StateRefTable, StateRefColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStateRefWith applies the HasEdge predicate on the "state_ref" edge with a given conditions (other predicates).
func HasStateRefWith(preds ...predicate.State) predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := newStateRefStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Company) predicate.Company {
	return predicate.Company(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Company) predicate.Company {
	return predicate.Company(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Company) predicate.Company {
	return predicate.Company(sql.NotPredicates(p))
}
