// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/subhasundardass/retui/ent/company"
	"github.com/subhasundardass/retui/ent/predicate"
)

// CompanyUpdate is the builder for updating Company entities.
type CompanyUpdate struct {
	config
	hooks    []Hook
	mutation *CompanyMutation
}

// Where appends a list predicates to the CompanyUpdate builder.
func (_u *CompanyUpdate) Where(ps ...predicate.Company) *CompanyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CompanyUpdate) SetName(v string) *CompanyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableName(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *CompanyUpdate) SetCode(v string) *CompanyUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableCode(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetLegalName sets the "legal_name" field.
func (_u *CompanyUpdate) SetLegalName(v string) *CompanyUpdate {
	_u.mutation.SetLegalName(v)
	return _u
}

// SetNillableLegalName sets the "legal_name" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableLegalName(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetLegalName(*v)
	}
	return _u
}

// ClearLegalName clears the value of the "legal_name" field.
func (_u *CompanyUpdate) ClearLegalName() *CompanyUpdate {
	_u.mutation.ClearLegalName()
	return _u
}

// SetEmail sets the "email" field.
func (_u *CompanyUpdate) SetEmail(v string) *CompanyUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableEmail(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *CompanyUpdate) ClearEmail() *CompanyUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *CompanyUpdate) SetPhone(v string) *CompanyUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillablePhone(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *CompanyUpdate) ClearPhone() *CompanyUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetWebsite sets the "website" field.
func (_u *CompanyUpdate) SetWebsite(v string) *CompanyUpdate {
	_u.mutation.SetWebsite(v)
	return _u
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableWebsite(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetWebsite(*v)
	}
	return _u
}

// ClearWebsite clears the value of the "website" field.
func (_u *CompanyUpdate) ClearWebsite() *CompanyUpdate {
	_u.mutation.ClearWebsite()
	return _u
}

// SetTaxID sets the "tax_id" field.
func (_u *CompanyUpdate) SetTaxID(v string) *CompanyUpdate {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableTaxID(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// ClearTaxID clears the value of the "tax_id" field.
func (_u *CompanyUpdate) ClearTaxID() *CompanyUpdate {
	_u.mutation.ClearTaxID()
	return _u
}

// SetGstin sets the "gstin" field.
func (_u *CompanyUpdate) SetGstin(v string) *CompanyUpdate {
	_u.mutation.SetGstin(v)
	return _u
}

// SetNillableGstin sets the "gstin" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableGstin(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetGstin(*v)
	}
	return _u
}

// ClearGstin clears the value of the "gstin" field.
func (_u *CompanyUpdate) ClearGstin() *CompanyUpdate {
	_u.mutation.ClearGstin()
	return _u
}

// SetPan sets the "pan" field.
func (_u *CompanyUpdate) SetPan(v string) *CompanyUpdate {
	_u.mutation.SetPan(v)
	return _u
}

// SetNillablePan sets the "pan" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillablePan(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetPan(*v)
	}
	return _u
}

// ClearPan clears the value of the "pan" field.
func (_u *CompanyUpdate) ClearPan() *CompanyUpdate {
	_u.mutation.ClearPan()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *CompanyUpdate) SetCurrency(v string) *CompanyUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableCurrency(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *CompanyUpdate) SetTimezone(v string) *CompanyUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableTimezone(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetLogo sets the "logo" field.
func (_u *CompanyUpdate) SetLogo(v string) *CompanyUpdate {
	_u.mutation.SetLogo(v)
	return _u
}

// SetNillableLogo sets the "logo" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableLogo(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetLogo(*v)
	}
	return _u
}

// ClearLogo clears the value of the "logo" field.
func (_u *CompanyUpdate) ClearLogo() *CompanyUpdate {
	_u.mutation.ClearLogo()
	return _u
}

// SetAddress sets the "address" field.
func (_u *CompanyUpdate) SetAddress(v string) *CompanyUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableAddress(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *CompanyUpdate) ClearAddress() *CompanyUpdate {
	_u.mutation.ClearAddress()
	return _u
}

// SetCity sets the "city" field.
func (_u *CompanyUpdate) SetCity(v string) *CompanyUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableCity(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *CompanyUpdate) ClearCity() *CompanyUpdate {
	_u.mutation.ClearCity()
	return _u
}

// SetState sets the "state" field.
func (_u *CompanyUpdate) SetState(v string) *CompanyUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableState(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *CompanyUpdate) ClearState() *CompanyUpdate {
	_u.mutation.ClearState()
	return _u
}

// SetCountry sets the "country" field.
func (_u *CompanyUpdate) SetCountry(v string) *CompanyUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableCountry(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetPostalCode sets the "postal_code" field.
func (_u *CompanyUpdate) SetPostalCode(v string) *CompanyUpdate {
	_u.mutation.SetPostalCode(v)
	return _u
}

// SetNillablePostalCode sets the "postal_code" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillablePostalCode(v *string) *CompanyUpdate {
	if v != nil {
		_u.SetPostalCode(*v)
	}
	return _u
}

// ClearPostalCode clears the value of the "postal_code" field.
func (_u *CompanyUpdate) ClearPostalCode() *CompanyUpdate {
	_u.mutation.ClearPostalCode()
	return _u
}

// SetActive sets the "active" field.
func (_u *CompanyUpdate) SetActive(v bool) *CompanyUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *CompanyUpdate) SetNillableActive(v *bool) *CompanyUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CompanyUpdate) SetUpdatedAt(v time.Time) *CompanyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CompanyMutation object of the builder.
func (_u *CompanyUpdate) Mutation() *CompanyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CompanyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompanyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CompanyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompanyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CompanyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := company.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CompanyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := company.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Company.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := company.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Company.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LegalName(); ok {
		if err := company.LegalNameValidator(v); err != nil {
			return &ValidationError{Name: "legal_name", err: fmt.Errorf(`ent: validator failed for field "Company.legal_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := company.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Company.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxID(); ok {
		if err := company.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "Company.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Gstin(); ok {
		if err := company.GstinValidator(v); err != nil {
			return &ValidationError{Name: "gstin", err: fmt.Errorf(`ent: validator failed for field "Company.gstin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pan(); ok {
		if err := company.PanValidator(v); err != nil {
			return &ValidationError{Name: "pan", err: fmt.Errorf(`ent: validator failed for field "Company.pan": %w`, err)}
		}
	}
	return nil
}

func (_u *CompanyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(company.Table, company.Columns, sqlgraph.NewFieldSpec(company.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(company.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(company.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LegalName(); ok {
		_spec.SetField(company.FieldLegalName, field.TypeString, value)
	}
	if _u.mutation.LegalNameCleared() {
		_spec.ClearField(company.FieldLegalName, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(company.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(company.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(company.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(company.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Website(); ok {
		_spec.SetField(company.FieldWebsite, field.TypeString, value)
	}
	if _u.mutation.WebsiteCleared() {
		_spec.ClearField(company.FieldWebsite, field.TypeString)
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(company.FieldTaxID, field.TypeString, value)
	}
	if _u.mutation.TaxIDCleared() {
		_spec.ClearField(company.FieldTaxID, field.TypeString)
	}
	if value, ok := _u.mutation.Gstin(); ok {
		_spec.SetField(company.FieldGstin, field.TypeString, value)
	}
	if _u.mutation.GstinCleared() {
		_spec.ClearField(company.FieldGstin, field.TypeString)
	}
	if value, ok := _u.mutation.Pan(); ok {
		_spec.SetField(company.FieldPan, field.TypeString, value)
	}
	if _u.mutation.PanCleared() {
		_spec.ClearField(company.FieldPan, field.TypeString)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(company.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(company.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Logo(); ok {
		_spec.SetField(company.FieldLogo, field.TypeString, value)
	}
	if _u.mutation.LogoCleared() {
		_spec.ClearField(company.FieldLogo, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(company.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(company.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(company.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(company.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(company.FieldState, field.TypeString, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(company.FieldState, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(company.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostalCode(); ok {
		_spec.SetField(company.FieldPostalCode, field.TypeString, value)
	}
	if _u.mutation.PostalCodeCleared() {
		_spec.ClearField(company.FieldPostalCode, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(company.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(company.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{company.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CompanyUpdateOne is the builder for updating a single Company entity.
type CompanyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CompanyMutation
}

// SetName sets the "name" field.
func (_u *CompanyUpdateOne) SetName(v string) *CompanyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableName(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *CompanyUpdateOne) SetCode(v string) *CompanyUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableCode(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetLegalName sets the "legal_name" field.
func (_u *CompanyUpdateOne) SetLegalName(v string) *CompanyUpdateOne {
	_u.mutation.SetLegalName(v)
	return _u
}

// SetNillableLegalName sets the "legal_name" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableLegalName(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetLegalName(*v)
	}
	return _u
}

// ClearLegalName clears the value of the "legal_name" field.
func (_u *CompanyUpdateOne) ClearLegalName() *CompanyUpdateOne {
	_u.mutation.ClearLegalName()
	return _u
}

// SetEmail sets the "email" field.
func (_u *CompanyUpdateOne) SetEmail(v string) *CompanyUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableEmail(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *CompanyUpdateOne) ClearEmail() *CompanyUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *CompanyUpdateOne) SetPhone(v string) *CompanyUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillablePhone(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *CompanyUpdateOne) ClearPhone() *CompanyUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetWebsite sets the "website" field.
func (_u *CompanyUpdateOne) SetWebsite(v string) *CompanyUpdateOne {
	_u.mutation.SetWebsite(v)
	return _u
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableWebsite(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetWebsite(*v)
	}
	return _u
}

// ClearWebsite clears the value of the "website" field.
func (_u *CompanyUpdateOne) ClearWebsite() *CompanyUpdateOne {
	_u.mutation.ClearWebsite()
	return _u
}

// SetTaxID sets the "tax_id" field.
func (_u *CompanyUpdateOne) SetTaxID(v string) *CompanyUpdateOne {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableTaxID(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// ClearTaxID clears the value of the "tax_id" field.
func (_u *CompanyUpdateOne) ClearTaxID() *CompanyUpdateOne {
	_u.mutation.ClearTaxID()
	return _u
}

// SetGstin sets the "gstin" field.
func (_u *CompanyUpdateOne) SetGstin(v string) *CompanyUpdateOne {
	_u.mutation.SetGstin(v)
	return _u
}

// SetNillableGstin sets the "gstin" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableGstin(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetGstin(*v)
	}
	return _u
}

// ClearGstin clears the value of the "gstin" field.
func (_u *CompanyUpdateOne) ClearGstin() *CompanyUpdateOne {
	_u.mutation.ClearGstin()
	return _u
}

// SetPan sets the "pan" field.
func (_u *CompanyUpdateOne) SetPan(v string) *CompanyUpdateOne {
	_u.mutation.SetPan(v)
	return _u
}

// SetNillablePan sets the "pan" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillablePan(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetPan(*v)
	}
	return _u
}

// ClearPan clears the value of the "pan" field.
func (_u *CompanyUpdateOne) ClearPan() *CompanyUpdateOne {
	_u.mutation.ClearPan()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *CompanyUpdateOne) SetCurrency(v string) *CompanyUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableCurrency(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *CompanyUpdateOne) SetTimezone(v string) *CompanyUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableTimezone(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetLogo sets the "logo" field.
func (_u *CompanyUpdateOne) SetLogo(v string) *CompanyUpdateOne {
	_u.mutation.SetLogo(v)
	return _u
}

// SetNillableLogo sets the "logo" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableLogo(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetLogo(*v)
	}
	return _u
}

// ClearLogo clears the value of the "logo" field.
func (_u *CompanyUpdateOne) ClearLogo() *CompanyUpdateOne {
	_u.mutation.ClearLogo()
	return _u
}

// SetAddress sets the "address" field.
func (_u *CompanyUpdateOne) SetAddress(v string) *CompanyUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableAddress(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *CompanyUpdateOne) ClearAddress() *CompanyUpdateOne {
	_u.mutation.ClearAddress()
	return _u
}

// SetCity sets the "city" field.
func (_u *CompanyUpdateOne) SetCity(v string) *CompanyUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableCity(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *CompanyUpdateOne) ClearCity() *CompanyUpdateOne {
	_u.mutation.ClearCity()
	return _u
}

// SetState sets the "state" field.
func (_u *CompanyUpdateOne) SetState(v string) *CompanyUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableState(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *CompanyUpdateOne) ClearState() *CompanyUpdateOne {
	_u.mutation.ClearState()
	return _u
}

// SetCountry sets the "country" field.
func (_u *CompanyUpdateOne) SetCountry(v string) *CompanyUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableCountry(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetPostalCode sets the "postal_code" field.
func (_u *CompanyUpdateOne) SetPostalCode(v string) *CompanyUpdateOne {
	_u.mutation.SetPostalCode(v)
	return _u
}

// SetNillablePostalCode sets the "postal_code" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillablePostalCode(v *string) *CompanyUpdateOne {
	if v != nil {
		_u.SetPostalCode(*v)
	}
	return _u
}

// ClearPostalCode clears the value of the "postal_code" field.
func (_u *CompanyUpdateOne) ClearPostalCode() *CompanyUpdateOne {
	_u.mutation.ClearPostalCode()
	return _u
}

// SetActive sets the "active" field.
func (_u *CompanyUpdateOne) SetActive(v bool) *CompanyUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *CompanyUpdateOne) SetNillableActive(v *bool) *CompanyUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CompanyUpdateOne) SetUpdatedAt(v time.Time) *CompanyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CompanyMutation object of the builder.
func (_u *CompanyUpdateOne) Mutation() *CompanyMutation {
	return _u.mutation
}

// Where appends a list predicates to the CompanyUpdate builder.
func (_u *CompanyUpdateOne) Where(ps ...predicate.Company) *CompanyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CompanyUpdateOne) Select(field string, fields ...string) *CompanyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Company entity.
func (_u *CompanyUpdateOne) Save(ctx context.Context) (*Company, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompanyUpdateOne) SaveX(ctx context.Context) *Company {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CompanyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompanyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CompanyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := company.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CompanyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := company.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Company.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := company.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Company.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LegalName(); ok {
		if err := company.LegalNameValidator(v); err != nil {
			return &ValidationError{Name: "legal_name", err: fmt.Errorf(`ent: validator failed for field "Company.legal_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := company.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Company.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxID(); ok {
		if err := company.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "Company.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Gstin(); ok {
		if err := company.GstinValidator(v); err != nil {
			return &ValidationError{Name: "gstin", err: fmt.Errorf(`ent: validator failed for field "Company.gstin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pan(); ok {
		if err := company.PanValidator(v); err != nil {
			return &ValidationError{Name: "pan", err: fmt.Errorf(`ent: validator failed for field "Company.pan": %w`, err)}
		}
	}
	return nil
}

func (_u *CompanyUpdateOne) sqlSave(ctx context.Context) (_node *Company, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(company.Table, company.Columns, sqlgraph.NewFieldSpec(company.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Company.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, company.FieldID)
		for _, f := range fields {
			if !company.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != company.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(company.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(company.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LegalName(); ok {
		_spec.SetField(company.FieldLegalName, field.TypeString, value)
	}
	if _u.mutation.LegalNameCleared() {
		_spec.ClearField(company.FieldLegalName, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(company.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(company.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(company.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(company.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Website(); ok {
		_spec.SetField(company.FieldWebsite, field.TypeString, value)
	}
	if _u.mutation.WebsiteCleared() {
		_spec.ClearField(company.FieldWebsite, field.TypeString)
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(company.FieldTaxID, field.TypeString, value)
	}
	if _u.mutation.TaxIDCleared() {
		_spec.ClearField(company.FieldTaxID, field.TypeString)
	}
	if value, ok := _u.mutation.Gstin(); ok {
		_spec.SetField(company.FieldGstin, field.TypeString, value)
	}
	if _u.mutation.GstinCleared() {
		_spec.ClearField(company.FieldGstin, field.TypeString)
	}
	if value, ok := _u.mutation.Pan(); ok {
		_spec.SetField(company.FieldPan, field.TypeString, value)
	}
	if _u.mutation.PanCleared() {
		_spec.ClearField(company.FieldPan, field.TypeString)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(company.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(company.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Logo(); ok {
		_spec.SetField(company.FieldLogo, field.TypeString, value)
	}
	if _u.mutation.LogoCleared() {
		_spec.ClearField(company.FieldLogo, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(company.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(company.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(company.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(company.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(company.FieldState, field.TypeString, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(company.FieldState, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(company.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostalCode(); ok {
		_spec.SetField(company.FieldPostalCode, field.TypeString, value)
	}
	if _u.mutation.PostalCodeCleared() {
		_spec.ClearField(company.FieldPostalCode, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(company.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(company.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Company{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{company.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
