// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/subhasundardass/retui/ent/journal"
	"github.com/subhasundardass/retui/ent/journal_line"
	"github.com/subhasundardass/retui/ent/ledger"
	"github.com/subhasundardass/retui/ent/predicate"
)

// JournalLineUpdate is the builder for updating Journal_Line entities.
type JournalLineUpdate struct {
	config
	hooks    []Hook
	mutation *JournalLineMutation
}

// Where appends a list predicates to the JournalLineUpdate builder.
func (_u *JournalLineUpdate) Where(ps ...predicate.Journal_Line) *JournalLineUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *JournalLineUpdate) SetUpdateTime(v time.Time) *JournalLineUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetJournalID sets the "journal_id" field.
func (_u *JournalLineUpdate) SetJournalID(v int) *JournalLineUpdate {
	_u.mutation.SetJournalID(v)
	return _u
}

// SetNillableJournalID sets the "journal_id" field if the given value is not nil.
func (_u *JournalLineUpdate) SetNillableJournalID(v *int) *JournalLineUpdate {
	if v != nil {
		_u.SetJournalID(*v)
	}
	return _u
}

// SetLedgerID sets the "ledger_id" field.
func (_u *JournalLineUpdate) SetLedgerID(v int) *JournalLineUpdate {
	_u.mutation.SetLedgerID(v)
	return _u
}

// SetNillableLedgerID sets the "ledger_id" field if the given value is not nil.
func (_u *JournalLineUpdate) SetNillableLedgerID(v *int) *JournalLineUpdate {
	if v != nil {
		_u.SetLedgerID(*v)
	}
	return _u
}

// SetDebit sets the "debit" field.
func (_u *JournalLineUpdate) SetDebit(v float64) *JournalLineUpdate {
	_u.mutation.ResetDebit()
	_u.mutation.SetDebit(v)
	return _u
}

// SetNillableDebit sets the "debit" field if the given value is not nil.
func (_u *JournalLineUpdate) SetNillableDebit(v *float64) *JournalLineUpdate {
	if v != nil {
		_u.SetDebit(*v)
	}
	return _u
}

// AddDebit adds value to the "debit" field.
func (_u *JournalLineUpdate) AddDebit(v float64) *JournalLineUpdate {
	_u.mutation.AddDebit(v)
	return _u
}

// SetCredit sets the "credit" field.
func (_u *JournalLineUpdate) SetCredit(v float64) *JournalLineUpdate {
	_u.mutation.ResetCredit()
	_u.mutation.SetCredit(v)
	return _u
}

// SetNillableCredit sets the "credit" field if the given value is not nil.
func (_u *JournalLineUpdate) SetNillableCredit(v *float64) *JournalLineUpdate {
	if v != nil {
		_u.SetCredit(*v)
	}
	return _u
}

// AddCredit adds value to the "credit" field.
func (_u *JournalLineUpdate) AddCredit(v float64) *JournalLineUpdate {
	_u.mutation.AddCredit(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *JournalLineUpdate) SetDescription(v string) *JournalLineUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *JournalLineUpdate) SetNillableDescription(v *string) *JournalLineUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *JournalLineUpdate) ClearDescription() *JournalLineUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetReferenceType sets the "reference_type" field.
func (_u *JournalLineUpdate) SetReferenceType(v string) *JournalLineUpdate {
	_u.mutation.SetReferenceType(v)
	return _u
}

// SetNillableReferenceType sets the "reference_type" field if the given value is not nil.
func (_u *JournalLineUpdate) SetNillableReferenceType(v *string) *JournalLineUpdate {
	if v != nil {
		_u.SetReferenceType(*v)
	}
	return _u
}

// ClearReferenceType clears the value of the "reference_type" field.
func (_u *JournalLineUpdate) ClearReferenceType() *JournalLineUpdate {
	_u.mutation.ClearReferenceType()
	return _u
}

// SetReferenceID sets the "reference_id" field.
func (_u *JournalLineUpdate) SetReferenceID(v int) *JournalLineUpdate {
	_u.mutation.ResetReferenceID()
	_u.mutation.SetReferenceID(v)
	return _u
}

// SetNillableReferenceID sets the "reference_id" field if the given value is not nil.
func (_u *JournalLineUpdate) SetNillableReferenceID(v *int) *JournalLineUpdate {
	if v != nil {
		_u.SetReferenceID(*v)
	}
	return _u
}

// AddReferenceID adds value to the "reference_id" field.
func (_u *JournalLineUpdate) AddReferenceID(v int) *JournalLineUpdate {
	_u.mutation.AddReferenceID(v)
	return _u
}

// ClearReferenceID clears the value of the "reference_id" field.
func (_u *JournalLineUpdate) ClearReferenceID() *JournalLineUpdate {
	_u.mutation.ClearReferenceID()
	return _u
}

// SetLineNo sets the "line_no" field.
func (_u *JournalLineUpdate) SetLineNo(v int) *JournalLineUpdate {
	_u.mutation.ResetLineNo()
	_u.mutation.SetLineNo(v)
	return _u
}

// SetNillableLineNo sets the "line_no" field if the given value is not nil.
func (_u *JournalLineUpdate) SetNillableLineNo(v *int) *JournalLineUpdate {
	if v != nil {
		_u.SetLineNo(*v)
	}
	return _u
}

// AddLineNo adds value to the "line_no" field.
func (_u *JournalLineUpdate) AddLineNo(v int) *JournalLineUpdate {
	_u.mutation.AddLineNo(v)
	return _u
}

// SetJournal sets the "journal" edge to the Journal entity.
func (_u *JournalLineUpdate) SetJournal(v *Journal) *JournalLineUpdate {
	return _u.SetJournalID(v.ID)
}

// SetLedger sets the "ledger" edge to the Ledger entity.
func (_u *JournalLineUpdate) SetLedger(v *Ledger) *JournalLineUpdate {
	return _u.SetLedgerID(v.ID)
}

// Mutation returns the JournalLineMutation object of the builder.
func (_u *JournalLineUpdate) Mutation() *JournalLineMutation {
	return _u.mutation
}

// ClearJournal clears the "journal" edge to the Journal entity.
func (_u *JournalLineUpdate) ClearJournal() *JournalLineUpdate {
	_u.mutation.ClearJournal()
	return _u
}

// ClearLedger clears the "ledger" edge to the Ledger entity.
func (_u *JournalLineUpdate) ClearLedger() *JournalLineUpdate {
	_u.mutation.ClearLedger()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JournalLineUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JournalLineUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JournalLineUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JournalLineUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JournalLineUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := journal_line.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JournalLineUpdate) check() error {
	if _u.mutation.JournalCleared() && len(_u.mutation.JournalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Journal_Line.journal"`)
	}
	if _u.mutation.LedgerCleared() && len(_u.mutation.LedgerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Journal_Line.ledger"`)
	}
	return nil
}

func (_u *JournalLineUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(journal_line.Table, journal_line.Columns, sqlgraph.NewFieldSpec(journal_line.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(journal_line.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Debit(); ok {
		_spec.SetField(journal_line.FieldDebit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDebit(); ok {
		_spec.AddField(journal_line.FieldDebit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Credit(); ok {
		_spec.SetField(journal_line.FieldCredit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCredit(); ok {
		_spec.AddField(journal_line.FieldCredit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(journal_line.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(journal_line.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceType(); ok {
		_spec.SetField(journal_line.FieldReferenceType, field.TypeString, value)
	}
	if _u.mutation.ReferenceTypeCleared() {
		_spec.ClearField(journal_line.FieldReferenceType, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceID(); ok {
		_spec.SetField(journal_line.FieldReferenceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReferenceID(); ok {
		_spec.AddField(journal_line.FieldReferenceID, field.TypeInt, value)
	}
	if _u.mutation.ReferenceIDCleared() {
		_spec.ClearField(journal_line.FieldReferenceID, field.TypeInt)
	}
	if value, ok := _u.mutation.LineNo(); ok {
		_spec.SetField(journal_line.FieldLineNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLineNo(); ok {
		_spec.AddField(journal_line.FieldLineNo, field.TypeInt, value)
	}
	if _u.mutation.JournalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journal_line.JournalTable,
			Columns: []string{journal_line.JournalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journal.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JournalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journal_line.JournalTable,
			Columns: []string{journal_line.JournalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journal.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journal_line.LedgerTable,
			Columns: []string{journal_line.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journal_line.LedgerTable,
			Columns: []string{journal_line.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{journal_line.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JournalLineUpdateOne is the builder for updating a single Journal_Line entity.
type JournalLineUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JournalLineMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *JournalLineUpdateOne) SetUpdateTime(v time.Time) *JournalLineUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetJournalID sets the "journal_id" field.
func (_u *JournalLineUpdateOne) SetJournalID(v int) *JournalLineUpdateOne {
	_u.mutation.SetJournalID(v)
	return _u
}

// SetNillableJournalID sets the "journal_id" field if the given value is not nil.
func (_u *JournalLineUpdateOne) SetNillableJournalID(v *int) *JournalLineUpdateOne {
	if v != nil {
		_u.SetJournalID(*v)
	}
	return _u
}

// SetLedgerID sets the "ledger_id" field.
func (_u *JournalLineUpdateOne) SetLedgerID(v int) *JournalLineUpdateOne {
	_u.mutation.SetLedgerID(v)
	return _u
}

// SetNillableLedgerID sets the "ledger_id" field if the given value is not nil.
func (_u *JournalLineUpdateOne) SetNillableLedgerID(v *int) *JournalLineUpdateOne {
	if v != nil {
		_u.SetLedgerID(*v)
	}
	return _u
}

// SetDebit sets the "debit" field.
func (_u *JournalLineUpdateOne) SetDebit(v float64) *JournalLineUpdateOne {
	_u.mutation.ResetDebit()
	_u.mutation.SetDebit(v)
	return _u
}

// SetNillableDebit sets the "debit" field if the given value is not nil.
func (_u *JournalLineUpdateOne) SetNillableDebit(v *float64) *JournalLineUpdateOne {
	if v != nil {
		_u.SetDebit(*v)
	}
	return _u
}

// AddDebit adds value to the "debit" field.
func (_u *JournalLineUpdateOne) AddDebit(v float64) *JournalLineUpdateOne {
	_u.mutation.AddDebit(v)
	return _u
}

// SetCredit sets the "credit" field.
func (_u *JournalLineUpdateOne) SetCredit(v float64) *JournalLineUpdateOne {
	_u.mutation.ResetCredit()
	_u.mutation.SetCredit(v)
	return _u
}

// SetNillableCredit sets the "credit" field if the given value is not nil.
func (_u *JournalLineUpdateOne) SetNillableCredit(v *float64) *JournalLineUpdateOne {
	if v != nil {
		_u.SetCredit(*v)
	}
	return _u
}

// AddCredit adds value to the "credit" field.
func (_u *JournalLineUpdateOne) AddCredit(v float64) *JournalLineUpdateOne {
	_u.mutation.AddCredit(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *JournalLineUpdateOne) SetDescription(v string) *JournalLineUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *JournalLineUpdateOne) SetNillableDescription(v *string) *JournalLineUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *JournalLineUpdateOne) ClearDescription() *JournalLineUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetReferenceType sets the "reference_type" field.
func (_u *JournalLineUpdateOne) SetReferenceType(v string) *JournalLineUpdateOne {
	_u.mutation.SetReferenceType(v)
	return _u
}

// SetNillableReferenceType sets the "reference_type" field if the given value is not nil.
func (_u *JournalLineUpdateOne) SetNillableReferenceType(v *string) *JournalLineUpdateOne {
	if v != nil {
		_u.SetReferenceType(*v)
	}
	return _u
}

// ClearReferenceType clears the value of the "reference_type" field.
func (_u *JournalLineUpdateOne) ClearReferenceType() *JournalLineUpdateOne {
	_u.mutation.ClearReferenceType()
	return _u
}

// SetReferenceID sets the "reference_id" field.
func (_u *JournalLineUpdateOne) SetReferenceID(v int) *JournalLineUpdateOne {
	_u.mutation.ResetReferenceID()
	_u.mutation.SetReferenceID(v)
	return _u
}

// SetNillableReferenceID sets the "reference_id" field if the given value is not nil.
func (_u *JournalLineUpdateOne) SetNillableReferenceID(v *int) *JournalLineUpdateOne {
	if v != nil {
		_u.SetReferenceID(*v)
	}
	return _u
}

// AddReferenceID adds value to the "reference_id" field.
func (_u *JournalLineUpdateOne) AddReferenceID(v int) *JournalLineUpdateOne {
	_u.mutation.AddReferenceID(v)
	return _u
}

// ClearReferenceID clears the value of the "reference_id" field.
func (_u *JournalLineUpdateOne) ClearReferenceID() *JournalLineUpdateOne {
	_u.mutation.ClearReferenceID()
	return _u
}

// SetLineNo sets the "line_no" field.
func (_u *JournalLineUpdateOne) SetLineNo(v int) *JournalLineUpdateOne {
	_u.mutation.ResetLineNo()
	_u.mutation.SetLineNo(v)
	return _u
}

// SetNillableLineNo sets the "line_no" field if the given value is not nil.
func (_u *JournalLineUpdateOne) SetNillableLineNo(v *int) *JournalLineUpdateOne {
	if v != nil {
		_u.SetLineNo(*v)
	}
	return _u
}

// AddLineNo adds value to the "line_no" field.
func (_u *JournalLineUpdateOne) AddLineNo(v int) *JournalLineUpdateOne {
	_u.mutation.AddLineNo(v)
	return _u
}

// SetJournal sets the "journal" edge to the Journal entity.
func (_u *JournalLineUpdateOne) SetJournal(v *Journal) *JournalLineUpdateOne {
	return _u.SetJournalID(v.ID)
}

// SetLedger sets the "ledger" edge to the Ledger entity.
func (_u *JournalLineUpdateOne) SetLedger(v *Ledger) *JournalLineUpdateOne {
	return _u.SetLedgerID(v.ID)
}

// Mutation returns the JournalLineMutation object of the builder.
func (_u *JournalLineUpdateOne) Mutation() *JournalLineMutation {
	return _u.mutation
}

// ClearJournal clears the "journal" edge to the Journal entity.
func (_u *JournalLineUpdateOne) ClearJournal() *JournalLineUpdateOne {
	_u.mutation.ClearJournal()
	return _u
}

// ClearLedger clears the "ledger" edge to the Ledger entity.
func (_u *JournalLineUpdateOne) ClearLedger() *JournalLineUpdateOne {
	_u.mutation.ClearLedger()
	return _u
}

// Where appends a list predicates to the JournalLineUpdate builder.
func (_u *JournalLineUpdateOne) Where(ps ...predicate.Journal_Line) *JournalLineUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JournalLineUpdateOne) Select(field string, fields ...string) *JournalLineUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Journal_Line entity.
func (_u *JournalLineUpdateOne) Save(ctx context.Context) (*Journal_Line, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JournalLineUpdateOne) SaveX(ctx context.Context) *Journal_Line {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JournalLineUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JournalLineUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JournalLineUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := journal_line.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JournalLineUpdateOne) check() error {
	if _u.mutation.JournalCleared() && len(_u.mutation.JournalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Journal_Line.journal"`)
	}
	if _u.mutation.LedgerCleared() && len(_u.mutation.LedgerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Journal_Line.ledger"`)
	}
	return nil
}

func (_u *JournalLineUpdateOne) sqlSave(ctx context.Context) (_node *Journal_Line, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(journal_line.Table, journal_line.Columns, sqlgraph.NewFieldSpec(journal_line.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Journal_Line.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, journal_line.FieldID)
		for _, f := range fields {
			if !journal_line.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != journal_line.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(journal_line.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Debit(); ok {
		_spec.SetField(journal_line.FieldDebit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDebit(); ok {
		_spec.AddField(journal_line.FieldDebit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Credit(); ok {
		_spec.SetField(journal_line.FieldCredit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCredit(); ok {
		_spec.AddField(journal_line.FieldCredit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(journal_line.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(journal_line.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceType(); ok {
		_spec.SetField(journal_line.FieldReferenceType, field.TypeString, value)
	}
	if _u.mutation.ReferenceTypeCleared() {
		_spec.ClearField(journal_line.FieldReferenceType, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceID(); ok {
		_spec.SetField(journal_line.FieldReferenceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReferenceID(); ok {
		_spec.AddField(journal_line.FieldReferenceID, field.TypeInt, value)
	}
	if _u.mutation.ReferenceIDCleared() {
		_spec.ClearField(journal_line.FieldReferenceID, field.TypeInt)
	}
	if value, ok := _u.mutation.LineNo(); ok {
		_spec.SetField(journal_line.FieldLineNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLineNo(); ok {
		_spec.AddField(journal_line.FieldLineNo, field.TypeInt, value)
	}
	if _u.mutation.JournalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journal_line.JournalTable,
			Columns: []string{journal_line.JournalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journal.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JournalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journal_line.JournalTable,
			Columns: []string{journal_line.JournalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journal.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journal_line.LedgerTable,
			Columns: []string{journal_line.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journal_line.LedgerTable,
			Columns: []string{journal_line.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Journal_Line{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{journal_line.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
