// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/subhasundardass/retui/ent/journal"
	"github.com/subhasundardass/retui/ent/journal_line"
	"github.com/subhasundardass/retui/ent/ledger"
)

// Journal_Line is the model entity for the Journal_Line schema.
type Journal_Line struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// JournalID holds the value of the "journal_id" field.
	JournalID int `json:"journal_id,omitempty"`
	// LedgerID holds the value of the "ledger_id" field.
	LedgerID int `json:"ledger_id,omitempty"`
	// Debit holds the value of the "debit" field.
	Debit float64 `json:"debit,omitempty"`
	// Credit holds the value of the "credit" field.
	Credit float64 `json:"credit,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// ReferenceType holds the value of the "reference_type" field.
	ReferenceType *string `json:"reference_type,omitempty"`
	// ReferenceID holds the value of the "reference_id" field.
	ReferenceID *int `json:"reference_id,omitempty"`
	// LineNo holds the value of the "line_no" field.
	LineNo int `json:"line_no,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the Journal_LineQuery when eager-loading is set.
	Edges        Journal_LineEdges `json:"edges"`
	selectValues sql.SelectValues
}

// Journal_LineEdges holds the relations/edges for other nodes in the graph.
type Journal_LineEdges struct {
	// Journal holds the value of the journal edge.
	Journal *Journal `json:"journal,omitempty"`
	// Ledger holds the value of the ledger edge.
	Ledger *Ledger `json:"ledger,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// JournalOrErr returns the Journal value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Journal_LineEdges) JournalOrErr() (*Journal, error) {
	if e.Journal != nil {
		return e.Journal, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: journal.Label}
	}
	return nil, &NotLoadedError{edge: "journal"}
}

// LedgerOrErr returns the Ledger value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Journal_LineEdges) LedgerOrErr() (*Ledger, error) {
	if e.Ledger != nil {
		return e.Ledger, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: ledger.Label}
	}
	return nil, &NotLoadedError{edge: "ledger"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Journal_Line) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case journal_line.FieldDebit, journal_line.FieldCredit:
			values[i] = new(sql.NullFloat64)
		case journal_line.FieldID, journal_line.FieldJournalID, journal_line.FieldLedgerID, journal_line.FieldReferenceID, journal_line.FieldLineNo:
			values[i] = new(sql.NullInt64)
		case journal_line.FieldDescription, journal_line.FieldReferenceType:
			values[i] = new(sql.NullString)
		case journal_line.FieldCreateTime, journal_line.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Journal_Line fields.
func (_m *Journal_Line) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case journal_line.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case journal_line.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case journal_line.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case journal_line.FieldJournalID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field journal_id", values[i])
			} else if value.Valid {
				_m.JournalID = int(value.Int64)
			}
		case journal_line.FieldLedgerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ledger_id", values[i])
			} else if value.Valid {
				_m.LedgerID = int(value.Int64)
			}
		case journal_line.FieldDebit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field debit", values[i])
			} else if value.Valid {
				_m.Debit = value.Float64
			}
		case journal_line.FieldCredit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credit", values[i])
			} else if value.Valid {
				_m.Credit = value.Float64
			}
		case journal_line.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case journal_line.FieldReferenceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_type", values[i])
			} else if value.Valid {
				_m.ReferenceType = new(string)
				*_m.ReferenceType = value.String
			}
		case journal_line.FieldReferenceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reference_id", values[i])
			} else if value.Valid {
				_m.ReferenceID = new(int)
				*_m.ReferenceID = int(value.Int64)
			}
		case journal_line.FieldLineNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field line_no", values[i])
			} else if value.Valid {
				_m.LineNo = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Journal_Line.
// This includes values selected through modifiers, order, etc.
func (_m *Journal_Line) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryJournal queries the "journal" edge of the Journal_Line entity.
func (_m *Journal_Line) QueryJournal() *JournalQuery {
	return NewJournalLineClient(_m.config).QueryJournal(_m)
}

// QueryLedger queries the "ledger" edge of the Journal_Line entity.
func (_m *Journal_Line) QueryLedger() *LedgerQuery {
	return NewJournalLineClient(_m.config).QueryLedger(_m)
}

// Update returns a builder for updating this Journal_Line.
// Note that you need to call Journal_Line.Unwrap() before calling this method if this Journal_Line
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Journal_Line) Update() *JournalLineUpdateOne {
	return NewJournalLineClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Journal_Line entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Journal_Line) Unwrap() *Journal_Line {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Journal_Line is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Journal_Line) String() string {
	var builder strings.Builder
	builder.WriteString("Journal_Line(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("journal_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.JournalID))
	builder.WriteString(", ")
	builder.WriteString("ledger_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LedgerID))
	builder.WriteString(", ")
	builder.WriteString("debit=")
	builder.WriteString(fmt.Sprintf("%v", _m.Debit))
	builder.WriteString(", ")
	builder.WriteString("credit=")
	builder.WriteString(fmt.Sprintf("%v", _m.Credit))
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReferenceType; v != nil {
		builder.WriteString("reference_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReferenceID; v != nil {
		builder.WriteString("reference_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("line_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.LineNo))
	builder.WriteByte(')')
	return builder.String()
}

// Journal_Lines is a parsable slice of Journal_Line.
type Journal_Lines []*Journal_Line
