// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/subhasundardass/retui/ent/ledger"
	"github.com/subhasundardass/retui/ent/ledger_group"
)

// LedgerGroupCreate is the builder for creating a Ledger_Group entity.
type LedgerGroupCreate struct {
	config
	mutation *LedgerGroupMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *LedgerGroupCreate) SetCode(v string) *LedgerGroupCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *LedgerGroupCreate) SetName(v string) *LedgerGroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNature sets the "nature" field.
func (_c *LedgerGroupCreate) SetNature(v ledger_group.Nature) *LedgerGroupCreate {
	_c.mutation.SetNature(v)
	return _c
}

// SetIsSystem sets the "is_system" field.
func (_c *LedgerGroupCreate) SetIsSystem(v bool) *LedgerGroupCreate {
	_c.mutation.SetIsSystem(v)
	return _c
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_c *LedgerGroupCreate) SetNillableIsSystem(v *bool) *LedgerGroupCreate {
	if v != nil {
		_c.SetIsSystem(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *LedgerGroupCreate) SetDescription(v string) *LedgerGroupCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *LedgerGroupCreate) SetNillableDescription(v *string) *LedgerGroupCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// AddChildIDs adds the "children" edge to the Ledger_Group entity by IDs.
func (_c *LedgerGroupCreate) AddChildIDs(ids ...int) *LedgerGroupCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Ledger_Group entity.
func (_c *LedgerGroupCreate) AddChildren(v ...*Ledger_Group) *LedgerGroupCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// SetParentID sets the "parent" edge to the Ledger_Group entity by ID.
func (_c *LedgerGroupCreate) SetParentID(id int) *LedgerGroupCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the Ledger_Group entity by ID if the given value is not nil.
func (_c *LedgerGroupCreate) SetNillableParentID(id *int) *LedgerGroupCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the Ledger_Group entity.
func (_c *LedgerGroupCreate) SetParent(v *Ledger_Group) *LedgerGroupCreate {
	return _c.SetParentID(v.ID)
}

// AddLedgerIDs adds the "ledgers" edge to the Ledger entity by IDs.
func (_c *LedgerGroupCreate) AddLedgerIDs(ids ...int) *LedgerGroupCreate {
	_c.mutation.AddLedgerIDs(ids...)
	return _c
}

// AddLedgers adds the "ledgers" edges to the Ledger entity.
func (_c *LedgerGroupCreate) AddLedgers(v ...*Ledger) *LedgerGroupCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLedgerIDs(ids...)
}

// Mutation returns the LedgerGroupMutation object of the builder.
func (_c *LedgerGroupCreate) Mutation() *LedgerGroupMutation {
	return _c.mutation
}

// Save creates the Ledger_Group in the database.
func (_c *LedgerGroupCreate) Save(ctx context.Context) (*Ledger_Group, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LedgerGroupCreate) SaveX(ctx context.Context) *Ledger_Group {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LedgerGroupCreate) defaults() {
	if _, ok := _c.mutation.IsSystem(); !ok {
		v := ledger_group.DefaultIsSystem
		_c.mutation.SetIsSystem(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := ledger_group.DefaultDescription
		_c.mutation.SetDescription(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LedgerGroupCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Ledger_Group.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := ledger_group.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Ledger_Group.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Ledger_Group.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := ledger_group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Ledger_Group.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Nature(); !ok {
		return &ValidationError{Name: "nature", err: errors.New(`ent: missing required field "Ledger_Group.nature"`)}
	}
	if v, ok := _c.mutation.Nature(); ok {
		if err := ledger_group.NatureValidator(v); err != nil {
			return &ValidationError{Name: "nature", err: fmt.Errorf(`ent: validator failed for field "Ledger_Group.nature": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		return &ValidationError{Name: "is_system", err: errors.New(`ent: missing required field "Ledger_Group.is_system"`)}
	}
	return nil
}

func (_c *LedgerGroupCreate) sqlSave(ctx context.Context) (*Ledger_Group, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LedgerGroupCreate) createSpec() (*Ledger_Group, *sqlgraph.CreateSpec) {
	var (
		_node = &Ledger_Group{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ledger_group.Table, sqlgraph.NewFieldSpec(ledger_group.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(ledger_group.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ledger_group.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Nature(); ok {
		_spec.SetField(ledger_group.FieldNature, field.TypeEnum, value)
		_node.Nature = value
	}
	if value, ok := _c.mutation.IsSystem(); ok {
		_spec.SetField(ledger_group.FieldIsSystem, field.TypeBool, value)
		_node.IsSystem = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(ledger_group.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ledger_group.ChildrenTable,
			Columns: []string{ledger_group.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger_group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ledger_group.ParentTable,
			Columns: []string{ledger_group.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger_group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ledger_group_parent = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LedgersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger_group.LedgersTable,
			Columns: []string{ledger_group.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LedgerGroupCreateBulk is the builder for creating many Ledger_Group entities in bulk.
type LedgerGroupCreateBulk struct {
	config
	err      error
	builders []*LedgerGroupCreate
}

// Save creates the Ledger_Group entities in the database.
func (_c *LedgerGroupCreateBulk) Save(ctx context.Context) ([]*Ledger_Group, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ledger_Group, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LedgerGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LedgerGroupCreateBulk) SaveX(ctx context.Context) []*Ledger_Group {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
