// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/subhasundardass/retui/ent/journal_line"
	"github.com/subhasundardass/retui/ent/ledger"
	"github.com/subhasundardass/retui/ent/ledger_group"
	"github.com/subhasundardass/retui/ent/partymaster"
	"github.com/subhasundardass/retui/ent/predicate"
)

// LedgerQuery is the builder for querying Ledger entities.
type LedgerQuery struct {
	config
	ctx              *QueryContext
	order            []ledger.OrderOption
	inters           []Interceptor
	predicates       []predicate.Ledger
	withGroup        *LedgerGroupQuery
	withParty        *PartyMasterQuery
	withJournalLines *JournalLineQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LedgerQuery builder.
func (_q *LedgerQuery) Where(ps ...predicate.Ledger) *LedgerQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *LedgerQuery) Limit(limit int) *LedgerQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *LedgerQuery) Offset(offset int) *LedgerQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *LedgerQuery) Unique(unique bool) *LedgerQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *LedgerQuery) Order(o ...ledger.OrderOption) *LedgerQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGroup chains the current query on the "group" edge.
func (_q *LedgerQuery) QueryGroup() *LedgerGroupQuery {
	query := (&LedgerGroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ledger.Table, ledger.FieldID, selector),
			sqlgraph.To(ledger_group.Table, ledger_group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ledger.GroupTable, ledger.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParty chains the current query on the "party" edge.
func (_q *LedgerQuery) QueryParty() *PartyMasterQuery {
	query := (&PartyMasterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ledger.Table, ledger.FieldID, selector),
			sqlgraph.To(partymaster.Table, partymaster.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ledger.PartyTable, ledger.PartyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryJournalLines chains the current query on the "journal_lines" edge.
func (_q *LedgerQuery) QueryJournalLines() *JournalLineQuery {
	query := (&JournalLineClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ledger.Table, ledger.FieldID, selector),
			sqlgraph.To(journal_line.Table, journal_line.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ledger.JournalLinesTable, ledger.JournalLinesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Ledger entity from the query.
// Returns a *NotFoundError when no Ledger was found.
func (_q *LedgerQuery) First(ctx context.Context) (*Ledger, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ledger.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *LedgerQuery) FirstX(ctx context.Context) *Ledger {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Ledger ID from the query.
// Returns a *NotFoundError when no Ledger ID was found.
func (_q *LedgerQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ledger.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *LedgerQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Ledger entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Ledger entity is found.
// Returns a *NotFoundError when no Ledger entities are found.
func (_q *LedgerQuery) Only(ctx context.Context) (*Ledger, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ledger.Label}
	default:
		return nil, &NotSingularError{ledger.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *LedgerQuery) OnlyX(ctx context.Context) *Ledger {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Ledger ID in the query.
// Returns a *NotSingularError when more than one Ledger ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *LedgerQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ledger.Label}
	default:
		err = &NotSingularError{ledger.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *LedgerQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Ledgers.
func (_q *LedgerQuery) All(ctx context.Context) ([]*Ledger, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Ledger, *LedgerQuery]()
	return withInterceptors[[]*Ledger](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *LedgerQuery) AllX(ctx context.Context) []*Ledger {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Ledger IDs.
func (_q *LedgerQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(ledger.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *LedgerQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *LedgerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*LedgerQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *LedgerQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *LedgerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *LedgerQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LedgerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *LedgerQuery) Clone() *LedgerQuery {
	if _q == nil {
		return nil
	}
	return &LedgerQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]ledger.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Ledger{}, _q.predicates...),
		withGroup:        _q.withGroup.Clone(),
		withParty:        _q.withParty.Clone(),
		withJournalLines: _q.withJournalLines.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LedgerQuery) WithGroup(opts ...func(*LedgerGroupQuery)) *LedgerQuery {
	query := (&LedgerGroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// WithParty tells the query-builder to eager-load the nodes that are connected to
// the "party" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LedgerQuery) WithParty(opts ...func(*PartyMasterQuery)) *LedgerQuery {
	query := (&PartyMasterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParty = query
	return _q
}

// WithJournalLines tells the query-builder to eager-load the nodes that are connected to
// the "journal_lines" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LedgerQuery) WithJournalLines(opts ...func(*JournalLineQuery)) *LedgerQuery {
	query := (&JournalLineClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withJournalLines = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Ledger.Query().
//		GroupBy(ledger.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *LedgerQuery) GroupBy(field string, fields ...string) *LedgerGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LedgerGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = ledger.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.Ledger.Query().
//		Select(ledger.FieldCreateTime).
//		Scan(ctx, &v)
func (_q *LedgerQuery) Select(fields ...string) *LedgerSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &LedgerSelect{LedgerQuery: _q}
	sbuild.label = ledger.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LedgerSelect configured with the given aggregations.
func (_q *LedgerQuery) Aggregate(fns ...AggregateFunc) *LedgerSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *LedgerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !ledger.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *LedgerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Ledger, error) {
	var (
		nodes       = []*Ledger{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withGroup != nil,
			_q.withParty != nil,
			_q.withJournalLines != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, ledger.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Ledger).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Ledger{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *Ledger, e *Ledger_Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withParty; query != nil {
		if err := _q.loadParty(ctx, query, nodes, nil,
			func(n *Ledger, e *PartyMaster) { n.Edges.Party = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withJournalLines; query != nil {
		if err := _q.loadJournalLines(ctx, query, nodes,
			func(n *Ledger) { n.Edges.JournalLines = []*Journal_Line{} },
			func(n *Ledger, e *Journal_Line) { n.Edges.JournalLines = append(n.Edges.JournalLines, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *LedgerQuery) loadGroup(ctx context.Context, query *LedgerGroupQuery, nodes []*Ledger, init func(*Ledger), assign func(*Ledger, *Ledger_Group)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Ledger)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(ledger_group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *LedgerQuery) loadParty(ctx context.Context, query *PartyMasterQuery, nodes []*Ledger, init func(*Ledger), assign func(*Ledger, *PartyMaster)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Ledger)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(partymaster.FieldLedgerID)
	}
	query.Where(predicate.PartyMaster(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(ledger.PartyColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LedgerID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ledger_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *LedgerQuery) loadJournalLines(ctx context.Context, query *JournalLineQuery, nodes []*Ledger, init func(*Ledger), assign func(*Ledger, *Journal_Line)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Ledger)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(journal_line.FieldLedgerID)
	}
	query.Where(predicate.Journal_Line(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(ledger.JournalLinesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LedgerID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ledger_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *LedgerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *LedgerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ledger.Table, ledger.Columns, sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ledger.FieldID)
		for i := range fields {
			if fields[i] != ledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(ledger.FieldGroupID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *LedgerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(ledger.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = ledger.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LedgerGroupBy is the group-by builder for Ledger entities.
type LedgerGroupBy struct {
	selector
	build *LedgerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *LedgerGroupBy) Aggregate(fns ...AggregateFunc) *LedgerGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *LedgerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LedgerQuery, *LedgerGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *LedgerGroupBy) sqlScan(ctx context.Context, root *LedgerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LedgerSelect is the builder for selecting fields of Ledger entities.
type LedgerSelect struct {
	*LedgerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *LedgerSelect) Aggregate(fns ...AggregateFunc) *LedgerSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *LedgerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LedgerQuery, *LedgerSelect](ctx, _s.LedgerQuery, _s, _s.inters, v)
}

func (_s *LedgerSelect) sqlScan(ctx context.Context, root *LedgerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
