// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/subhasundardass/retui/ent/country"
	"github.com/subhasundardass/retui/ent/journal_line"
	"github.com/subhasundardass/retui/ent/ledger"
	"github.com/subhasundardass/retui/ent/ledger_group"
	"github.com/subhasundardass/retui/ent/state"
)

// LedgerCreate is the builder for creating a Ledger entity.
type LedgerCreate struct {
	config
	mutation *LedgerMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *LedgerCreate) SetCreateTime(v time.Time) *LedgerCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableCreateTime(v *time.Time) *LedgerCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *LedgerCreate) SetUpdateTime(v time.Time) *LedgerCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableUpdateTime(v *time.Time) *LedgerCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *LedgerCreate) SetGroupID(v int) *LedgerCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *LedgerCreate) SetCode(v string) *LedgerCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *LedgerCreate) SetName(v string) *LedgerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAlias sets the "alias" field.
func (_c *LedgerCreate) SetAlias(v string) *LedgerCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableAlias(v *string) *LedgerCreate {
	if v != nil {
		_c.SetAlias(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *LedgerCreate) SetDescription(v string) *LedgerCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableDescription(v *string) *LedgerCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetBalance sets the "balance" field.
func (_c *LedgerCreate) SetBalance(v float64) *LedgerCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableBalance(v *float64) *LedgerCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetPartyType sets the "party_type" field.
func (_c *LedgerCreate) SetPartyType(v ledger.PartyType) *LedgerCreate {
	_c.mutation.SetPartyType(v)
	return _c
}

// SetNillablePartyType sets the "party_type" field if the given value is not nil.
func (_c *LedgerCreate) SetNillablePartyType(v *ledger.PartyType) *LedgerCreate {
	if v != nil {
		_c.SetPartyType(*v)
	}
	return _c
}

// SetAddressLine1 sets the "address_line1" field.
func (_c *LedgerCreate) SetAddressLine1(v string) *LedgerCreate {
	_c.mutation.SetAddressLine1(v)
	return _c
}

// SetNillableAddressLine1 sets the "address_line1" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableAddressLine1(v *string) *LedgerCreate {
	if v != nil {
		_c.SetAddressLine1(*v)
	}
	return _c
}

// SetAddressLine2 sets the "address_line2" field.
func (_c *LedgerCreate) SetAddressLine2(v string) *LedgerCreate {
	_c.mutation.SetAddressLine2(v)
	return _c
}

// SetNillableAddressLine2 sets the "address_line2" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableAddressLine2(v *string) *LedgerCreate {
	if v != nil {
		_c.SetAddressLine2(*v)
	}
	return _c
}

// SetCity sets the "city" field.
func (_c *LedgerCreate) SetCity(v string) *LedgerCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableCity(v *string) *LedgerCreate {
	if v != nil {
		_c.SetCity(*v)
	}
	return _c
}

// SetStateID sets the "state_id" field.
func (_c *LedgerCreate) SetStateID(v int) *LedgerCreate {
	_c.mutation.SetStateID(v)
	return _c
}

// SetNillableStateID sets the "state_id" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableStateID(v *int) *LedgerCreate {
	if v != nil {
		_c.SetStateID(*v)
	}
	return _c
}

// SetCountryID sets the "country_id" field.
func (_c *LedgerCreate) SetCountryID(v int) *LedgerCreate {
	_c.mutation.SetCountryID(v)
	return _c
}

// SetNillableCountryID sets the "country_id" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableCountryID(v *int) *LedgerCreate {
	if v != nil {
		_c.SetCountryID(*v)
	}
	return _c
}

// SetPincode sets the "pincode" field.
func (_c *LedgerCreate) SetPincode(v string) *LedgerCreate {
	_c.mutation.SetPincode(v)
	return _c
}

// SetNillablePincode sets the "pincode" field if the given value is not nil.
func (_c *LedgerCreate) SetNillablePincode(v *string) *LedgerCreate {
	if v != nil {
		_c.SetPincode(*v)
	}
	return _c
}

// SetPhone sets the "phone" field.
func (_c *LedgerCreate) SetPhone(v string) *LedgerCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *LedgerCreate) SetNillablePhone(v *string) *LedgerCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetMobile sets the "mobile" field.
func (_c *LedgerCreate) SetMobile(v string) *LedgerCreate {
	_c.mutation.SetMobile(v)
	return _c
}

// SetNillableMobile sets the "mobile" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableMobile(v *string) *LedgerCreate {
	if v != nil {
		_c.SetMobile(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *LedgerCreate) SetEmail(v string) *LedgerCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableEmail(v *string) *LedgerCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetContactPerson sets the "contact_person" field.
func (_c *LedgerCreate) SetContactPerson(v string) *LedgerCreate {
	_c.mutation.SetContactPerson(v)
	return _c
}

// SetNillableContactPerson sets the "contact_person" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableContactPerson(v *string) *LedgerCreate {
	if v != nil {
		_c.SetContactPerson(*v)
	}
	return _c
}

// SetGstRegistrationType sets the "gst_registration_type" field.
func (_c *LedgerCreate) SetGstRegistrationType(v ledger.GstRegistrationType) *LedgerCreate {
	_c.mutation.SetGstRegistrationType(v)
	return _c
}

// SetNillableGstRegistrationType sets the "gst_registration_type" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableGstRegistrationType(v *ledger.GstRegistrationType) *LedgerCreate {
	if v != nil {
		_c.SetGstRegistrationType(*v)
	}
	return _c
}

// SetGstin sets the "gstin" field.
func (_c *LedgerCreate) SetGstin(v string) *LedgerCreate {
	_c.mutation.SetGstin(v)
	return _c
}

// SetNillableGstin sets the "gstin" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableGstin(v *string) *LedgerCreate {
	if v != nil {
		_c.SetGstin(*v)
	}
	return _c
}

// SetPan sets the "pan" field.
func (_c *LedgerCreate) SetPan(v string) *LedgerCreate {
	_c.mutation.SetPan(v)
	return _c
}

// SetNillablePan sets the "pan" field if the given value is not nil.
func (_c *LedgerCreate) SetNillablePan(v *string) *LedgerCreate {
	if v != nil {
		_c.SetPan(*v)
	}
	return _c
}

// SetBankName sets the "bank_name" field.
func (_c *LedgerCreate) SetBankName(v string) *LedgerCreate {
	_c.mutation.SetBankName(v)
	return _c
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableBankName(v *string) *LedgerCreate {
	if v != nil {
		_c.SetBankName(*v)
	}
	return _c
}

// SetBankAccountNo sets the "bank_account_no" field.
func (_c *LedgerCreate) SetBankAccountNo(v string) *LedgerCreate {
	_c.mutation.SetBankAccountNo(v)
	return _c
}

// SetNillableBankAccountNo sets the "bank_account_no" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableBankAccountNo(v *string) *LedgerCreate {
	if v != nil {
		_c.SetBankAccountNo(*v)
	}
	return _c
}

// SetBankIfsc sets the "bank_ifsc" field.
func (_c *LedgerCreate) SetBankIfsc(v string) *LedgerCreate {
	_c.mutation.SetBankIfsc(v)
	return _c
}

// SetNillableBankIfsc sets the "bank_ifsc" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableBankIfsc(v *string) *LedgerCreate {
	if v != nil {
		_c.SetBankIfsc(*v)
	}
	return _c
}

// SetBankBranch sets the "bank_branch" field.
func (_c *LedgerCreate) SetBankBranch(v string) *LedgerCreate {
	_c.mutation.SetBankBranch(v)
	return _c
}

// SetNillableBankBranch sets the "bank_branch" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableBankBranch(v *string) *LedgerCreate {
	if v != nil {
		_c.SetBankBranch(*v)
	}
	return _c
}

// SetIsSystem sets the "is_system" field.
func (_c *LedgerCreate) SetIsSystem(v bool) *LedgerCreate {
	_c.mutation.SetIsSystem(v)
	return _c
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableIsSystem(v *bool) *LedgerCreate {
	if v != nil {
		_c.SetIsSystem(*v)
	}
	return _c
}

// SetIsParty sets the "is_party" field.
func (_c *LedgerCreate) SetIsParty(v bool) *LedgerCreate {
	_c.mutation.SetIsParty(v)
	return _c
}

// SetNillableIsParty sets the "is_party" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableIsParty(v *bool) *LedgerCreate {
	if v != nil {
		_c.SetIsParty(*v)
	}
	return _c
}

// SetIsBank sets the "is_bank" field.
func (_c *LedgerCreate) SetIsBank(v bool) *LedgerCreate {
	_c.mutation.SetIsBank(v)
	return _c
}

// SetNillableIsBank sets the "is_bank" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableIsBank(v *bool) *LedgerCreate {
	if v != nil {
		_c.SetIsBank(*v)
	}
	return _c
}

// SetIsCash sets the "is_cash" field.
func (_c *LedgerCreate) SetIsCash(v bool) *LedgerCreate {
	_c.mutation.SetIsCash(v)
	return _c
}

// SetNillableIsCash sets the "is_cash" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableIsCash(v *bool) *LedgerCreate {
	if v != nil {
		_c.SetIsCash(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *LedgerCreate) SetIsActive(v bool) *LedgerCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableIsActive(v *bool) *LedgerCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LedgerCreate) SetID(v int) *LedgerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetGroup sets the "group" edge to the Ledger_Group entity.
func (_c *LedgerCreate) SetGroup(v *Ledger_Group) *LedgerCreate {
	return _c.SetGroupID(v.ID)
}

// SetState sets the "state" edge to the State entity.
func (_c *LedgerCreate) SetState(v *State) *LedgerCreate {
	return _c.SetStateID(v.ID)
}

// SetCountry sets the "country" edge to the Country entity.
func (_c *LedgerCreate) SetCountry(v *Country) *LedgerCreate {
	return _c.SetCountryID(v.ID)
}

// AddJournalLineIDs adds the "journal_lines" edge to the Journal_Line entity by IDs.
func (_c *LedgerCreate) AddJournalLineIDs(ids ...int) *LedgerCreate {
	_c.mutation.AddJournalLineIDs(ids...)
	return _c
}

// AddJournalLines adds the "journal_lines" edges to the Journal_Line entity.
func (_c *LedgerCreate) AddJournalLines(v ...*Journal_Line) *LedgerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddJournalLineIDs(ids...)
}

// Mutation returns the LedgerMutation object of the builder.
func (_c *LedgerCreate) Mutation() *LedgerMutation {
	return _c.mutation
}

// Save creates the Ledger in the database.
func (_c *LedgerCreate) Save(ctx context.Context) (*Ledger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LedgerCreate) SaveX(ctx context.Context) *Ledger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LedgerCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := ledger.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := ledger.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Alias(); !ok {
		v := ledger.DefaultAlias
		_c.mutation.SetAlias(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := ledger.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Balance(); !ok {
		v := ledger.DefaultBalance
		_c.mutation.SetBalance(v)
	}
	if _, ok := _c.mutation.PartyType(); !ok {
		v := ledger.DefaultPartyType
		_c.mutation.SetPartyType(v)
	}
	if _, ok := _c.mutation.AddressLine1(); !ok {
		v := ledger.DefaultAddressLine1
		_c.mutation.SetAddressLine1(v)
	}
	if _, ok := _c.mutation.AddressLine2(); !ok {
		v := ledger.DefaultAddressLine2
		_c.mutation.SetAddressLine2(v)
	}
	if _, ok := _c.mutation.City(); !ok {
		v := ledger.DefaultCity
		_c.mutation.SetCity(v)
	}
	if _, ok := _c.mutation.Pincode(); !ok {
		v := ledger.DefaultPincode
		_c.mutation.SetPincode(v)
	}
	if _, ok := _c.mutation.Phone(); !ok {
		v := ledger.DefaultPhone
		_c.mutation.SetPhone(v)
	}
	if _, ok := _c.mutation.Mobile(); !ok {
		v := ledger.DefaultMobile
		_c.mutation.SetMobile(v)
	}
	if _, ok := _c.mutation.Email(); !ok {
		v := ledger.DefaultEmail
		_c.mutation.SetEmail(v)
	}
	if _, ok := _c.mutation.ContactPerson(); !ok {
		v := ledger.DefaultContactPerson
		_c.mutation.SetContactPerson(v)
	}
	if _, ok := _c.mutation.GstRegistrationType(); !ok {
		v := ledger.DefaultGstRegistrationType
		_c.mutation.SetGstRegistrationType(v)
	}
	if _, ok := _c.mutation.Gstin(); !ok {
		v := ledger.DefaultGstin
		_c.mutation.SetGstin(v)
	}
	if _, ok := _c.mutation.Pan(); !ok {
		v := ledger.DefaultPan
		_c.mutation.SetPan(v)
	}
	if _, ok := _c.mutation.BankName(); !ok {
		v := ledger.DefaultBankName
		_c.mutation.SetBankName(v)
	}
	if _, ok := _c.mutation.BankAccountNo(); !ok {
		v := ledger.DefaultBankAccountNo
		_c.mutation.SetBankAccountNo(v)
	}
	if _, ok := _c.mutation.BankIfsc(); !ok {
		v := ledger.DefaultBankIfsc
		_c.mutation.SetBankIfsc(v)
	}
	if _, ok := _c.mutation.BankBranch(); !ok {
		v := ledger.DefaultBankBranch
		_c.mutation.SetBankBranch(v)
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		v := ledger.DefaultIsSystem
		_c.mutation.SetIsSystem(v)
	}
	if _, ok := _c.mutation.IsParty(); !ok {
		v := ledger.DefaultIsParty
		_c.mutation.SetIsParty(v)
	}
	if _, ok := _c.mutation.IsBank(); !ok {
		v := ledger.DefaultIsBank
		_c.mutation.SetIsBank(v)
	}
	if _, ok := _c.mutation.IsCash(); !ok {
		v := ledger.DefaultIsCash
		_c.mutation.SetIsCash(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := ledger.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LedgerCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Ledger.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Ledger.update_time"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "Ledger.group_id"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Ledger.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := ledger.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Ledger.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Ledger.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := ledger.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Ledger.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Alias(); ok {
		if err := ledger.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "Ledger.alias": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "Ledger.balance"`)}
	}
	if _, ok := _c.mutation.PartyType(); !ok {
		return &ValidationError{Name: "party_type", err: errors.New(`ent: missing required field "Ledger.party_type"`)}
	}
	if v, ok := _c.mutation.PartyType(); ok {
		if err := ledger.PartyTypeValidator(v); err != nil {
			return &ValidationError{Name: "party_type", err: fmt.Errorf(`ent: validator failed for field "Ledger.party_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AddressLine1(); ok {
		if err := ledger.AddressLine1Validator(v); err != nil {
			return &ValidationError{Name: "address_line1", err: fmt.Errorf(`ent: validator failed for field "Ledger.address_line1": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AddressLine2(); ok {
		if err := ledger.AddressLine2Validator(v); err != nil {
			return &ValidationError{Name: "address_line2", err: fmt.Errorf(`ent: validator failed for field "Ledger.address_line2": %w`, err)}
		}
	}
	if v, ok := _c.mutation.City(); ok {
		if err := ledger.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Ledger.city": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Pincode(); ok {
		if err := ledger.PincodeValidator(v); err != nil {
			return &ValidationError{Name: "pincode", err: fmt.Errorf(`ent: validator failed for field "Ledger.pincode": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := ledger.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Ledger.phone": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Mobile(); ok {
		if err := ledger.MobileValidator(v); err != nil {
			return &ValidationError{Name: "mobile", err: fmt.Errorf(`ent: validator failed for field "Ledger.mobile": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := ledger.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Ledger.email": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ContactPerson(); ok {
		if err := ledger.ContactPersonValidator(v); err != nil {
			return &ValidationError{Name: "contact_person", err: fmt.Errorf(`ent: validator failed for field "Ledger.contact_person": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GstRegistrationType(); !ok {
		return &ValidationError{Name: "gst_registration_type", err: errors.New(`ent: missing required field "Ledger.gst_registration_type"`)}
	}
	if v, ok := _c.mutation.GstRegistrationType(); ok {
		if err := ledger.GstRegistrationTypeValidator(v); err != nil {
			return &ValidationError{Name: "gst_registration_type", err: fmt.Errorf(`ent: validator failed for field "Ledger.gst_registration_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Gstin(); ok {
		if err := ledger.GstinValidator(v); err != nil {
			return &ValidationError{Name: "gstin", err: fmt.Errorf(`ent: validator failed for field "Ledger.gstin": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Pan(); ok {
		if err := ledger.PanValidator(v); err != nil {
			return &ValidationError{Name: "pan", err: fmt.Errorf(`ent: validator failed for field "Ledger.pan": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BankName(); ok {
		if err := ledger.BankNameValidator(v); err != nil {
			return &ValidationError{Name: "bank_name", err: fmt.Errorf(`ent: validator failed for field "Ledger.bank_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BankAccountNo(); ok {
		if err := ledger.BankAccountNoValidator(v); err != nil {
			return &ValidationError{Name: "bank_account_no", err: fmt.Errorf(`ent: validator failed for field "Ledger.bank_account_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BankIfsc(); ok {
		if err := ledger.BankIfscValidator(v); err != nil {
			return &ValidationError{Name: "bank_ifsc", err: fmt.Errorf(`ent: validator failed for field "Ledger.bank_ifsc": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BankBranch(); ok {
		if err := ledger.BankBranchValidator(v); err != nil {
			return &ValidationError{Name: "bank_branch", err: fmt.Errorf(`ent: validator failed for field "Ledger.bank_branch": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		return &ValidationError{Name: "is_system", err: errors.New(`ent: missing required field "Ledger.is_system"`)}
	}
	if _, ok := _c.mutation.IsParty(); !ok {
		return &ValidationError{Name: "is_party", err: errors.New(`ent: missing required field "Ledger.is_party"`)}
	}
	if _, ok := _c.mutation.IsBank(); !ok {
		return &ValidationError{Name: "is_bank", err: errors.New(`ent: missing required field "Ledger.is_bank"`)}
	}
	if _, ok := _c.mutation.IsCash(); !ok {
		return &ValidationError{Name: "is_cash", err: errors.New(`ent: missing required field "Ledger.is_cash"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Ledger.is_active"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "Ledger.group"`)}
	}
	return nil
}

func (_c *LedgerCreate) sqlSave(ctx context.Context) (*Ledger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LedgerCreate) createSpec() (*Ledger, *sqlgraph.CreateSpec) {
	var (
		_node = &Ledger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ledger.Table, sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(ledger.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(ledger.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(ledger.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ledger.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(ledger.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(ledger.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(ledger.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.PartyType(); ok {
		_spec.SetField(ledger.FieldPartyType, field.TypeEnum, value)
		_node.PartyType = value
	}
	if value, ok := _c.mutation.AddressLine1(); ok {
		_spec.SetField(ledger.FieldAddressLine1, field.TypeString, value)
		_node.AddressLine1 = value
	}
	if value, ok := _c.mutation.AddressLine2(); ok {
		_spec.SetField(ledger.FieldAddressLine2, field.TypeString, value)
		_node.AddressLine2 = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(ledger.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.Pincode(); ok {
		_spec.SetField(ledger.FieldPincode, field.TypeString, value)
		_node.Pincode = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(ledger.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Mobile(); ok {
		_spec.SetField(ledger.FieldMobile, field.TypeString, value)
		_node.Mobile = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(ledger.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.ContactPerson(); ok {
		_spec.SetField(ledger.FieldContactPerson, field.TypeString, value)
		_node.ContactPerson = value
	}
	if value, ok := _c.mutation.GstRegistrationType(); ok {
		_spec.SetField(ledger.FieldGstRegistrationType, field.TypeEnum, value)
		_node.GstRegistrationType = value
	}
	if value, ok := _c.mutation.Gstin(); ok {
		_spec.SetField(ledger.FieldGstin, field.TypeString, value)
		_node.Gstin = value
	}
	if value, ok := _c.mutation.Pan(); ok {
		_spec.SetField(ledger.FieldPan, field.TypeString, value)
		_node.Pan = value
	}
	if value, ok := _c.mutation.BankName(); ok {
		_spec.SetField(ledger.FieldBankName, field.TypeString, value)
		_node.BankName = value
	}
	if value, ok := _c.mutation.BankAccountNo(); ok {
		_spec.SetField(ledger.FieldBankAccountNo, field.TypeString, value)
		_node.BankAccountNo = value
	}
	if value, ok := _c.mutation.BankIfsc(); ok {
		_spec.SetField(ledger.FieldBankIfsc, field.TypeString, value)
		_node.BankIfsc = value
	}
	if value, ok := _c.mutation.BankBranch(); ok {
		_spec.SetField(ledger.FieldBankBranch, field.TypeString, value)
		_node.BankBranch = value
	}
	if value, ok := _c.mutation.IsSystem(); ok {
		_spec.SetField(ledger.FieldIsSystem, field.TypeBool, value)
		_node.IsSystem = value
	}
	if value, ok := _c.mutation.IsParty(); ok {
		_spec.SetField(ledger.FieldIsParty, field.TypeBool, value)
		_node.IsParty = value
	}
	if value, ok := _c.mutation.IsBank(); ok {
		_spec.SetField(ledger.FieldIsBank, field.TypeBool, value)
		_node.IsBank = value
	}
	if value, ok := _c.mutation.IsCash(); ok {
		_spec.SetField(ledger.FieldIsCash, field.TypeBool, value)
		_node.IsCash = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(ledger.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ledger.GroupTable,
			Columns: []string{ledger.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger_group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ledger.StateTable,
			Columns: []string{ledger.StateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(state.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StateID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CountryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ledger.CountryTable,
			Columns: []string{ledger.CountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(country.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CountryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.JournalLinesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.JournalLinesTable,
			Columns: []string{ledger.JournalLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journal_line.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LedgerCreateBulk is the builder for creating many Ledger entities in bulk.
type LedgerCreateBulk struct {
	config
	err      error
	builders []*LedgerCreate
}

// Save creates the Ledger entities in the database.
func (_c *LedgerCreateBulk) Save(ctx context.Context) ([]*Ledger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ledger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LedgerCreateBulk) SaveX(ctx context.Context) []*Ledger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
