// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/subhasundardass/retui/ent/journal_line"
	"github.com/subhasundardass/retui/ent/ledger"
	"github.com/subhasundardass/retui/ent/ledger_group"
	"github.com/subhasundardass/retui/ent/partymaster"
	"github.com/subhasundardass/retui/ent/predicate"
)

// LedgerUpdate is the builder for updating Ledger entities.
type LedgerUpdate struct {
	config
	hooks    []Hook
	mutation *LedgerMutation
}

// Where appends a list predicates to the LedgerUpdate builder.
func (_u *LedgerUpdate) Where(ps ...predicate.Ledger) *LedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *LedgerUpdate) SetUpdateTime(v time.Time) *LedgerUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *LedgerUpdate) SetGroupID(v int) *LedgerUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillableGroupID(v *int) *LedgerUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *LedgerUpdate) SetCode(v string) *LedgerUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillableCode(v *string) *LedgerUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *LedgerUpdate) SetName(v string) *LedgerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillableName(v *string) *LedgerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAlias sets the "alias" field.
func (_u *LedgerUpdate) SetAlias(v string) *LedgerUpdate {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillableAlias(v *string) *LedgerUpdate {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// ClearAlias clears the value of the "alias" field.
func (_u *LedgerUpdate) ClearAlias() *LedgerUpdate {
	_u.mutation.ClearAlias()
	return _u
}

// SetDescription sets the "description" field.
func (_u *LedgerUpdate) SetDescription(v string) *LedgerUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillableDescription(v *string) *LedgerUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *LedgerUpdate) ClearDescription() *LedgerUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetOpeningBalance sets the "opening_balance" field.
func (_u *LedgerUpdate) SetOpeningBalance(v float64) *LedgerUpdate {
	_u.mutation.ResetOpeningBalance()
	_u.mutation.SetOpeningBalance(v)
	return _u
}

// SetNillableOpeningBalance sets the "opening_balance" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillableOpeningBalance(v *float64) *LedgerUpdate {
	if v != nil {
		_u.SetOpeningBalance(*v)
	}
	return _u
}

// AddOpeningBalance adds value to the "opening_balance" field.
func (_u *LedgerUpdate) AddOpeningBalance(v float64) *LedgerUpdate {
	_u.mutation.AddOpeningBalance(v)
	return _u
}

// SetBalance sets the "balance" field.
func (_u *LedgerUpdate) SetBalance(v float64) *LedgerUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillableBalance(v *float64) *LedgerUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *LedgerUpdate) AddBalance(v float64) *LedgerUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *LedgerUpdate) SetIsSystem(v bool) *LedgerUpdate {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillableIsSystem(v *bool) *LedgerUpdate {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetIsParty sets the "is_party" field.
func (_u *LedgerUpdate) SetIsParty(v bool) *LedgerUpdate {
	_u.mutation.SetIsParty(v)
	return _u
}

// SetNillableIsParty sets the "is_party" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillableIsParty(v *bool) *LedgerUpdate {
	if v != nil {
		_u.SetIsParty(*v)
	}
	return _u
}

// SetIsBank sets the "is_bank" field.
func (_u *LedgerUpdate) SetIsBank(v bool) *LedgerUpdate {
	_u.mutation.SetIsBank(v)
	return _u
}

// SetNillableIsBank sets the "is_bank" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillableIsBank(v *bool) *LedgerUpdate {
	if v != nil {
		_u.SetIsBank(*v)
	}
	return _u
}

// SetIsCash sets the "is_cash" field.
func (_u *LedgerUpdate) SetIsCash(v bool) *LedgerUpdate {
	_u.mutation.SetIsCash(v)
	return _u
}

// SetNillableIsCash sets the "is_cash" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillableIsCash(v *bool) *LedgerUpdate {
	if v != nil {
		_u.SetIsCash(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Ledger_Group entity.
func (_u *LedgerUpdate) SetGroup(v *Ledger_Group) *LedgerUpdate {
	return _u.SetGroupID(v.ID)
}

// SetPartyID sets the "party" edge to the PartyMaster entity by ID.
func (_u *LedgerUpdate) SetPartyID(id int) *LedgerUpdate {
	_u.mutation.SetPartyID(id)
	return _u
}

// SetNillablePartyID sets the "party" edge to the PartyMaster entity by ID if the given value is not nil.
func (_u *LedgerUpdate) SetNillablePartyID(id *int) *LedgerUpdate {
	if id != nil {
		_u = _u.SetPartyID(*id)
	}
	return _u
}

// SetParty sets the "party" edge to the PartyMaster entity.
func (_u *LedgerUpdate) SetParty(v *PartyMaster) *LedgerUpdate {
	return _u.SetPartyID(v.ID)
}

// AddJournalLineIDs adds the "journal_lines" edge to the Journal_Line entity by IDs.
func (_u *LedgerUpdate) AddJournalLineIDs(ids ...int) *LedgerUpdate {
	_u.mutation.AddJournalLineIDs(ids...)
	return _u
}

// AddJournalLines adds the "journal_lines" edges to the Journal_Line entity.
func (_u *LedgerUpdate) AddJournalLines(v ...*Journal_Line) *LedgerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJournalLineIDs(ids...)
}

// Mutation returns the LedgerMutation object of the builder.
func (_u *LedgerUpdate) Mutation() *LedgerMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Ledger_Group entity.
func (_u *LedgerUpdate) ClearGroup() *LedgerUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearParty clears the "party" edge to the PartyMaster entity.
func (_u *LedgerUpdate) ClearParty() *LedgerUpdate {
	_u.mutation.ClearParty()
	return _u
}

// ClearJournalLines clears all "journal_lines" edges to the Journal_Line entity.
func (_u *LedgerUpdate) ClearJournalLines() *LedgerUpdate {
	_u.mutation.ClearJournalLines()
	return _u
}

// RemoveJournalLineIDs removes the "journal_lines" edge to Journal_Line entities by IDs.
func (_u *LedgerUpdate) RemoveJournalLineIDs(ids ...int) *LedgerUpdate {
	_u.mutation.RemoveJournalLineIDs(ids...)
	return _u
}

// RemoveJournalLines removes "journal_lines" edges to Journal_Line entities.
func (_u *LedgerUpdate) RemoveJournalLines(v ...*Journal_Line) *LedgerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJournalLineIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LedgerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LedgerUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := ledger.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LedgerUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := ledger.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Ledger.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := ledger.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Ledger.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Alias(); ok {
		if err := ledger.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "Ledger.alias": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ledger.group"`)
	}
	return nil
}

func (_u *LedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ledger.Table, ledger.Columns, sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(ledger.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(ledger.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ledger.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(ledger.FieldAlias, field.TypeString, value)
	}
	if _u.mutation.AliasCleared() {
		_spec.ClearField(ledger.FieldAlias, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ledger.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(ledger.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.OpeningBalance(); ok {
		_spec.SetField(ledger.FieldOpeningBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOpeningBalance(); ok {
		_spec.AddField(ledger.FieldOpeningBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(ledger.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(ledger.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(ledger.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsParty(); ok {
		_spec.SetField(ledger.FieldIsParty, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsBank(); ok {
		_spec.SetField(ledger.FieldIsBank, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsCash(); ok {
		_spec.SetField(ledger.FieldIsCash, field.TypeBool, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ledger.GroupTable,
			Columns: []string{ledger.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger_group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ledger.GroupTable,
			Columns: []string{ledger.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger_group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PartyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   ledger.PartyTable,
			Columns: []string{ledger.PartyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partymaster.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PartyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   ledger.PartyTable,
			Columns: []string{ledger.PartyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partymaster.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JournalLinesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.JournalLinesTable,
			Columns: []string{ledger.JournalLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journal_line.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJournalLinesIDs(); len(nodes) > 0 && !_u.mutation.JournalLinesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.JournalLinesTable,
			Columns: []string{ledger.JournalLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journal_line.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JournalLinesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.JournalLinesTable,
			Columns: []string{ledger.JournalLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journal_line.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LedgerUpdateOne is the builder for updating a single Ledger entity.
type LedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LedgerMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *LedgerUpdateOne) SetUpdateTime(v time.Time) *LedgerUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *LedgerUpdateOne) SetGroupID(v int) *LedgerUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillableGroupID(v *int) *LedgerUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *LedgerUpdateOne) SetCode(v string) *LedgerUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillableCode(v *string) *LedgerUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *LedgerUpdateOne) SetName(v string) *LedgerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillableName(v *string) *LedgerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAlias sets the "alias" field.
func (_u *LedgerUpdateOne) SetAlias(v string) *LedgerUpdateOne {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillableAlias(v *string) *LedgerUpdateOne {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// ClearAlias clears the value of the "alias" field.
func (_u *LedgerUpdateOne) ClearAlias() *LedgerUpdateOne {
	_u.mutation.ClearAlias()
	return _u
}

// SetDescription sets the "description" field.
func (_u *LedgerUpdateOne) SetDescription(v string) *LedgerUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillableDescription(v *string) *LedgerUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *LedgerUpdateOne) ClearDescription() *LedgerUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetOpeningBalance sets the "opening_balance" field.
func (_u *LedgerUpdateOne) SetOpeningBalance(v float64) *LedgerUpdateOne {
	_u.mutation.ResetOpeningBalance()
	_u.mutation.SetOpeningBalance(v)
	return _u
}

// SetNillableOpeningBalance sets the "opening_balance" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillableOpeningBalance(v *float64) *LedgerUpdateOne {
	if v != nil {
		_u.SetOpeningBalance(*v)
	}
	return _u
}

// AddOpeningBalance adds value to the "opening_balance" field.
func (_u *LedgerUpdateOne) AddOpeningBalance(v float64) *LedgerUpdateOne {
	_u.mutation.AddOpeningBalance(v)
	return _u
}

// SetBalance sets the "balance" field.
func (_u *LedgerUpdateOne) SetBalance(v float64) *LedgerUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillableBalance(v *float64) *LedgerUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *LedgerUpdateOne) AddBalance(v float64) *LedgerUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *LedgerUpdateOne) SetIsSystem(v bool) *LedgerUpdateOne {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillableIsSystem(v *bool) *LedgerUpdateOne {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetIsParty sets the "is_party" field.
func (_u *LedgerUpdateOne) SetIsParty(v bool) *LedgerUpdateOne {
	_u.mutation.SetIsParty(v)
	return _u
}

// SetNillableIsParty sets the "is_party" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillableIsParty(v *bool) *LedgerUpdateOne {
	if v != nil {
		_u.SetIsParty(*v)
	}
	return _u
}

// SetIsBank sets the "is_bank" field.
func (_u *LedgerUpdateOne) SetIsBank(v bool) *LedgerUpdateOne {
	_u.mutation.SetIsBank(v)
	return _u
}

// SetNillableIsBank sets the "is_bank" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillableIsBank(v *bool) *LedgerUpdateOne {
	if v != nil {
		_u.SetIsBank(*v)
	}
	return _u
}

// SetIsCash sets the "is_cash" field.
func (_u *LedgerUpdateOne) SetIsCash(v bool) *LedgerUpdateOne {
	_u.mutation.SetIsCash(v)
	return _u
}

// SetNillableIsCash sets the "is_cash" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillableIsCash(v *bool) *LedgerUpdateOne {
	if v != nil {
		_u.SetIsCash(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Ledger_Group entity.
func (_u *LedgerUpdateOne) SetGroup(v *Ledger_Group) *LedgerUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetPartyID sets the "party" edge to the PartyMaster entity by ID.
func (_u *LedgerUpdateOne) SetPartyID(id int) *LedgerUpdateOne {
	_u.mutation.SetPartyID(id)
	return _u
}

// SetNillablePartyID sets the "party" edge to the PartyMaster entity by ID if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillablePartyID(id *int) *LedgerUpdateOne {
	if id != nil {
		_u = _u.SetPartyID(*id)
	}
	return _u
}

// SetParty sets the "party" edge to the PartyMaster entity.
func (_u *LedgerUpdateOne) SetParty(v *PartyMaster) *LedgerUpdateOne {
	return _u.SetPartyID(v.ID)
}

// AddJournalLineIDs adds the "journal_lines" edge to the Journal_Line entity by IDs.
func (_u *LedgerUpdateOne) AddJournalLineIDs(ids ...int) *LedgerUpdateOne {
	_u.mutation.AddJournalLineIDs(ids...)
	return _u
}

// AddJournalLines adds the "journal_lines" edges to the Journal_Line entity.
func (_u *LedgerUpdateOne) AddJournalLines(v ...*Journal_Line) *LedgerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJournalLineIDs(ids...)
}

// Mutation returns the LedgerMutation object of the builder.
func (_u *LedgerUpdateOne) Mutation() *LedgerMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Ledger_Group entity.
func (_u *LedgerUpdateOne) ClearGroup() *LedgerUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearParty clears the "party" edge to the PartyMaster entity.
func (_u *LedgerUpdateOne) ClearParty() *LedgerUpdateOne {
	_u.mutation.ClearParty()
	return _u
}

// ClearJournalLines clears all "journal_lines" edges to the Journal_Line entity.
func (_u *LedgerUpdateOne) ClearJournalLines() *LedgerUpdateOne {
	_u.mutation.ClearJournalLines()
	return _u
}

// RemoveJournalLineIDs removes the "journal_lines" edge to Journal_Line entities by IDs.
func (_u *LedgerUpdateOne) RemoveJournalLineIDs(ids ...int) *LedgerUpdateOne {
	_u.mutation.RemoveJournalLineIDs(ids...)
	return _u
}

// RemoveJournalLines removes "journal_lines" edges to Journal_Line entities.
func (_u *LedgerUpdateOne) RemoveJournalLines(v ...*Journal_Line) *LedgerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJournalLineIDs(ids...)
}

// Where appends a list predicates to the LedgerUpdate builder.
func (_u *LedgerUpdateOne) Where(ps ...predicate.Ledger) *LedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LedgerUpdateOne) Select(field string, fields ...string) *LedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Ledger entity.
func (_u *LedgerUpdateOne) Save(ctx context.Context) (*Ledger, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerUpdateOne) SaveX(ctx context.Context) *Ledger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LedgerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := ledger.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LedgerUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := ledger.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Ledger.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := ledger.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Ledger.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Alias(); ok {
		if err := ledger.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "Ledger.alias": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ledger.group"`)
	}
	return nil
}

func (_u *LedgerUpdateOne) sqlSave(ctx context.Context) (_node *Ledger, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ledger.Table, ledger.Columns, sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ledger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ledger.FieldID)
		for _, f := range fields {
			if !ledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(ledger.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(ledger.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ledger.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(ledger.FieldAlias, field.TypeString, value)
	}
	if _u.mutation.AliasCleared() {
		_spec.ClearField(ledger.FieldAlias, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ledger.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(ledger.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.OpeningBalance(); ok {
		_spec.SetField(ledger.FieldOpeningBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOpeningBalance(); ok {
		_spec.AddField(ledger.FieldOpeningBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(ledger.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(ledger.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(ledger.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsParty(); ok {
		_spec.SetField(ledger.FieldIsParty, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsBank(); ok {
		_spec.SetField(ledger.FieldIsBank, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsCash(); ok {
		_spec.SetField(ledger.FieldIsCash, field.TypeBool, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ledger.GroupTable,
			Columns: []string{ledger.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger_group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ledger.GroupTable,
			Columns: []string{ledger.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger_group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PartyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   ledger.PartyTable,
			Columns: []string{ledger.PartyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partymaster.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PartyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   ledger.PartyTable,
			Columns: []string{ledger.PartyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partymaster.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JournalLinesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.JournalLinesTable,
			Columns: []string{ledger.JournalLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journal_line.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJournalLinesIDs(); len(nodes) > 0 && !_u.mutation.JournalLinesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.JournalLinesTable,
			Columns: []string{ledger.JournalLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journal_line.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JournalLinesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.JournalLinesTable,
			Columns: []string{ledger.JournalLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journal_line.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Ledger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
