// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/subhasundardass/retui/ent/company"
	"github.com/subhasundardass/retui/ent/country"
	"github.com/subhasundardass/retui/ent/journal"
	"github.com/subhasundardass/retui/ent/journal_line"
	"github.com/subhasundardass/retui/ent/ledger"
	"github.com/subhasundardass/retui/ent/ledger_group"
	"github.com/subhasundardass/retui/ent/partymaster"
	"github.com/subhasundardass/retui/ent/schema"
	"github.com/subhasundardass/retui/ent/settings"
	"github.com/subhasundardass/retui/ent/state"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	companyFields := schema.Company{}.Fields()
	_ = companyFields
	// companyDescName is the schema descriptor for name field.
	companyDescName := companyFields[0].Descriptor()
	// company.NameValidator is a validator for the "name" field. It is called by the builders before save.
	company.NameValidator = func() func(string) error {
		validators := companyDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// companyDescCode is the schema descriptor for code field.
	companyDescCode := companyFields[1].Descriptor()
	// company.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	company.CodeValidator = func() func(string) error {
		validators := companyDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// companyDescLegalName is the schema descriptor for legal_name field.
	companyDescLegalName := companyFields[2].Descriptor()
	// company.LegalNameValidator is a validator for the "legal_name" field. It is called by the builders before save.
	company.LegalNameValidator = companyDescLegalName.Validators[0].(func(string) error)
	// companyDescPhone is the schema descriptor for phone field.
	companyDescPhone := companyFields[4].Descriptor()
	// company.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	company.PhoneValidator = companyDescPhone.Validators[0].(func(string) error)
	// companyDescTaxID is the schema descriptor for tax_id field.
	companyDescTaxID := companyFields[6].Descriptor()
	// company.TaxIDValidator is a validator for the "tax_id" field. It is called by the builders before save.
	company.TaxIDValidator = companyDescTaxID.Validators[0].(func(string) error)
	// companyDescGstin is the schema descriptor for gstin field.
	companyDescGstin := companyFields[7].Descriptor()
	// company.GstinValidator is a validator for the "gstin" field. It is called by the builders before save.
	company.GstinValidator = companyDescGstin.Validators[0].(func(string) error)
	// companyDescPan is the schema descriptor for pan field.
	companyDescPan := companyFields[8].Descriptor()
	// company.PanValidator is a validator for the "pan" field. It is called by the builders before save.
	company.PanValidator = companyDescPan.Validators[0].(func(string) error)
	// companyDescCurrency is the schema descriptor for currency field.
	companyDescCurrency := companyFields[9].Descriptor()
	// company.DefaultCurrency holds the default value on creation for the currency field.
	company.DefaultCurrency = companyDescCurrency.Default.(string)
	// companyDescTimezone is the schema descriptor for timezone field.
	companyDescTimezone := companyFields[10].Descriptor()
	// company.DefaultTimezone holds the default value on creation for the timezone field.
	company.DefaultTimezone = companyDescTimezone.Default.(string)
	// companyDescActive is the schema descriptor for active field.
	companyDescActive := companyFields[15].Descriptor()
	// company.DefaultActive holds the default value on creation for the active field.
	company.DefaultActive = companyDescActive.Default.(bool)
	// companyDescCreatedAt is the schema descriptor for created_at field.
	companyDescCreatedAt := companyFields[16].Descriptor()
	// company.DefaultCreatedAt holds the default value on creation for the created_at field.
	company.DefaultCreatedAt = companyDescCreatedAt.Default.(func() time.Time)
	// companyDescUpdatedAt is the schema descriptor for updated_at field.
	companyDescUpdatedAt := companyFields[17].Descriptor()
	// company.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	company.DefaultUpdatedAt = companyDescUpdatedAt.Default.(func() time.Time)
	// company.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	company.UpdateDefaultUpdatedAt = companyDescUpdatedAt.UpdateDefault.(func() time.Time)
	countryFields := schema.Country{}.Fields()
	_ = countryFields
	// countryDescName is the schema descriptor for name field.
	countryDescName := countryFields[0].Descriptor()
	// country.NameValidator is a validator for the "name" field. It is called by the builders before save.
	country.NameValidator = func() func(string) error {
		validators := countryDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// countryDescCode is the schema descriptor for code field.
	countryDescCode := countryFields[1].Descriptor()
	// country.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	country.CodeValidator = func() func(string) error {
		validators := countryDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	journalMixin := schema.Journal{}.Mixin()
	journalMixinFields0 := journalMixin[0].Fields()
	_ = journalMixinFields0
	journalFields := schema.Journal{}.Fields()
	_ = journalFields
	// journalDescCreateTime is the schema descriptor for create_time field.
	journalDescCreateTime := journalMixinFields0[0].Descriptor()
	// journal.DefaultCreateTime holds the default value on creation for the create_time field.
	journal.DefaultCreateTime = journalDescCreateTime.Default.(func() time.Time)
	// journalDescUpdateTime is the schema descriptor for update_time field.
	journalDescUpdateTime := journalMixinFields0[1].Descriptor()
	// journal.DefaultUpdateTime holds the default value on creation for the update_time field.
	journal.DefaultUpdateTime = journalDescUpdateTime.Default.(func() time.Time)
	// journal.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	journal.UpdateDefaultUpdateTime = journalDescUpdateTime.UpdateDefault.(func() time.Time)
	// journalDescVoucherType is the schema descriptor for voucher_type field.
	journalDescVoucherType := journalFields[1].Descriptor()
	// journal.VoucherTypeValidator is a validator for the "voucher_type" field. It is called by the builders before save.
	journal.VoucherTypeValidator = journalDescVoucherType.Validators[0].(func(string) error)
	// journalDescVoucherNo is the schema descriptor for voucher_no field.
	journalDescVoucherNo := journalFields[2].Descriptor()
	// journal.VoucherNoValidator is a validator for the "voucher_no" field. It is called by the builders before save.
	journal.VoucherNoValidator = journalDescVoucherNo.Validators[0].(func(string) error)
	// journalDescTotalDebit is the schema descriptor for total_debit field.
	journalDescTotalDebit := journalFields[13].Descriptor()
	// journal.DefaultTotalDebit holds the default value on creation for the total_debit field.
	journal.DefaultTotalDebit = journalDescTotalDebit.Default.(float64)
	// journalDescTotalCredit is the schema descriptor for total_credit field.
	journalDescTotalCredit := journalFields[14].Descriptor()
	// journal.DefaultTotalCredit holds the default value on creation for the total_credit field.
	journal.DefaultTotalCredit = journalDescTotalCredit.Default.(float64)
	journal_lineMixin := schema.Journal_Line{}.Mixin()
	journal_lineMixinFields0 := journal_lineMixin[0].Fields()
	_ = journal_lineMixinFields0
	journal_lineFields := schema.Journal_Line{}.Fields()
	_ = journal_lineFields
	// journal_lineDescCreateTime is the schema descriptor for create_time field.
	journal_lineDescCreateTime := journal_lineMixinFields0[0].Descriptor()
	// journal_line.DefaultCreateTime holds the default value on creation for the create_time field.
	journal_line.DefaultCreateTime = journal_lineDescCreateTime.Default.(func() time.Time)
	// journal_lineDescUpdateTime is the schema descriptor for update_time field.
	journal_lineDescUpdateTime := journal_lineMixinFields0[1].Descriptor()
	// journal_line.DefaultUpdateTime holds the default value on creation for the update_time field.
	journal_line.DefaultUpdateTime = journal_lineDescUpdateTime.Default.(func() time.Time)
	// journal_line.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	journal_line.UpdateDefaultUpdateTime = journal_lineDescUpdateTime.UpdateDefault.(func() time.Time)
	// journal_lineDescDebit is the schema descriptor for debit field.
	journal_lineDescDebit := journal_lineFields[2].Descriptor()
	// journal_line.DefaultDebit holds the default value on creation for the debit field.
	journal_line.DefaultDebit = journal_lineDescDebit.Default.(float64)
	// journal_lineDescCredit is the schema descriptor for credit field.
	journal_lineDescCredit := journal_lineFields[3].Descriptor()
	// journal_line.DefaultCredit holds the default value on creation for the credit field.
	journal_line.DefaultCredit = journal_lineDescCredit.Default.(float64)
	// journal_lineDescLineNo is the schema descriptor for line_no field.
	journal_lineDescLineNo := journal_lineFields[7].Descriptor()
	// journal_line.DefaultLineNo holds the default value on creation for the line_no field.
	journal_line.DefaultLineNo = journal_lineDescLineNo.Default.(int)
	ledgerMixin := schema.Ledger{}.Mixin()
	ledgerMixinFields0 := ledgerMixin[0].Fields()
	_ = ledgerMixinFields0
	ledgerFields := schema.Ledger{}.Fields()
	_ = ledgerFields
	// ledgerDescCreateTime is the schema descriptor for create_time field.
	ledgerDescCreateTime := ledgerMixinFields0[0].Descriptor()
	// ledger.DefaultCreateTime holds the default value on creation for the create_time field.
	ledger.DefaultCreateTime = ledgerDescCreateTime.Default.(func() time.Time)
	// ledgerDescUpdateTime is the schema descriptor for update_time field.
	ledgerDescUpdateTime := ledgerMixinFields0[1].Descriptor()
	// ledger.DefaultUpdateTime holds the default value on creation for the update_time field.
	ledger.DefaultUpdateTime = ledgerDescUpdateTime.Default.(func() time.Time)
	// ledger.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	ledger.UpdateDefaultUpdateTime = ledgerDescUpdateTime.UpdateDefault.(func() time.Time)
	// ledgerDescCode is the schema descriptor for code field.
	ledgerDescCode := ledgerFields[1].Descriptor()
	// ledger.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	ledger.CodeValidator = ledgerDescCode.Validators[0].(func(string) error)
	// ledgerDescName is the schema descriptor for name field.
	ledgerDescName := ledgerFields[2].Descriptor()
	// ledger.NameValidator is a validator for the "name" field. It is called by the builders before save.
	ledger.NameValidator = func() func(string) error {
		validators := ledgerDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// ledgerDescAlias is the schema descriptor for alias field.
	ledgerDescAlias := ledgerFields[3].Descriptor()
	// ledger.DefaultAlias holds the default value on creation for the alias field.
	ledger.DefaultAlias = ledgerDescAlias.Default.(string)
	// ledger.AliasValidator is a validator for the "alias" field. It is called by the builders before save.
	ledger.AliasValidator = ledgerDescAlias.Validators[0].(func(string) error)
	// ledgerDescDescription is the schema descriptor for description field.
	ledgerDescDescription := ledgerFields[4].Descriptor()
	// ledger.DefaultDescription holds the default value on creation for the description field.
	ledger.DefaultDescription = ledgerDescDescription.Default.(string)
	// ledgerDescOpeningBalance is the schema descriptor for opening_balance field.
	ledgerDescOpeningBalance := ledgerFields[5].Descriptor()
	// ledger.DefaultOpeningBalance holds the default value on creation for the opening_balance field.
	ledger.DefaultOpeningBalance = ledgerDescOpeningBalance.Default.(float64)
	// ledgerDescBalance is the schema descriptor for balance field.
	ledgerDescBalance := ledgerFields[6].Descriptor()
	// ledger.DefaultBalance holds the default value on creation for the balance field.
	ledger.DefaultBalance = ledgerDescBalance.Default.(float64)
	// ledgerDescIsSystem is the schema descriptor for is_system field.
	ledgerDescIsSystem := ledgerFields[7].Descriptor()
	// ledger.DefaultIsSystem holds the default value on creation for the is_system field.
	ledger.DefaultIsSystem = ledgerDescIsSystem.Default.(bool)
	// ledgerDescIsParty is the schema descriptor for is_party field.
	ledgerDescIsParty := ledgerFields[8].Descriptor()
	// ledger.DefaultIsParty holds the default value on creation for the is_party field.
	ledger.DefaultIsParty = ledgerDescIsParty.Default.(bool)
	// ledgerDescIsBank is the schema descriptor for is_bank field.
	ledgerDescIsBank := ledgerFields[9].Descriptor()
	// ledger.DefaultIsBank holds the default value on creation for the is_bank field.
	ledger.DefaultIsBank = ledgerDescIsBank.Default.(bool)
	// ledgerDescIsCash is the schema descriptor for is_cash field.
	ledgerDescIsCash := ledgerFields[10].Descriptor()
	// ledger.DefaultIsCash holds the default value on creation for the is_cash field.
	ledger.DefaultIsCash = ledgerDescIsCash.Default.(bool)
	// ledgerDescIsActive is the schema descriptor for is_active field.
	ledgerDescIsActive := ledgerFields[11].Descriptor()
	// ledger.DefaultIsActive holds the default value on creation for the is_active field.
	ledger.DefaultIsActive = ledgerDescIsActive.Default.(bool)
	ledger_groupFields := schema.Ledger_Group{}.Fields()
	_ = ledger_groupFields
	// ledger_groupDescCode is the schema descriptor for code field.
	ledger_groupDescCode := ledger_groupFields[0].Descriptor()
	// ledger_group.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	ledger_group.CodeValidator = ledger_groupDescCode.Validators[0].(func(string) error)
	// ledger_groupDescName is the schema descriptor for name field.
	ledger_groupDescName := ledger_groupFields[1].Descriptor()
	// ledger_group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	ledger_group.NameValidator = func() func(string) error {
		validators := ledger_groupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// ledger_groupDescIsSystem is the schema descriptor for is_system field.
	ledger_groupDescIsSystem := ledger_groupFields[3].Descriptor()
	// ledger_group.DefaultIsSystem holds the default value on creation for the is_system field.
	ledger_group.DefaultIsSystem = ledger_groupDescIsSystem.Default.(bool)
	// ledger_groupDescDescription is the schema descriptor for description field.
	ledger_groupDescDescription := ledger_groupFields[4].Descriptor()
	// ledger_group.DefaultDescription holds the default value on creation for the description field.
	ledger_group.DefaultDescription = ledger_groupDescDescription.Default.(string)
	partymasterMixin := schema.PartyMaster{}.Mixin()
	partymasterMixinFields0 := partymasterMixin[0].Fields()
	_ = partymasterMixinFields0
	partymasterFields := schema.PartyMaster{}.Fields()
	_ = partymasterFields
	// partymasterDescCreateTime is the schema descriptor for create_time field.
	partymasterDescCreateTime := partymasterMixinFields0[0].Descriptor()
	// partymaster.DefaultCreateTime holds the default value on creation for the create_time field.
	partymaster.DefaultCreateTime = partymasterDescCreateTime.Default.(func() time.Time)
	// partymasterDescUpdateTime is the schema descriptor for update_time field.
	partymasterDescUpdateTime := partymasterMixinFields0[1].Descriptor()
	// partymaster.DefaultUpdateTime holds the default value on creation for the update_time field.
	partymaster.DefaultUpdateTime = partymasterDescUpdateTime.Default.(func() time.Time)
	// partymaster.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	partymaster.UpdateDefaultUpdateTime = partymasterDescUpdateTime.UpdateDefault.(func() time.Time)
	// partymasterDescDisplayName is the schema descriptor for display_name field.
	partymasterDescDisplayName := partymasterFields[2].Descriptor()
	// partymaster.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	partymaster.DisplayNameValidator = partymasterDescDisplayName.Validators[0].(func(string) error)
	// partymasterDescCreditLimit is the schema descriptor for credit_limit field.
	partymasterDescCreditLimit := partymasterFields[11].Descriptor()
	// partymaster.DefaultCreditLimit holds the default value on creation for the credit_limit field.
	partymaster.DefaultCreditLimit = partymasterDescCreditLimit.Default.(float64)
	// partymasterDescCreditDays is the schema descriptor for credit_days field.
	partymasterDescCreditDays := partymasterFields[12].Descriptor()
	// partymaster.DefaultCreditDays holds the default value on creation for the credit_days field.
	partymaster.DefaultCreditDays = partymasterDescCreditDays.Default.(int)
	// partymasterDescOpeningBalance is the schema descriptor for opening_balance field.
	partymasterDescOpeningBalance := partymasterFields[13].Descriptor()
	// partymaster.DefaultOpeningBalance holds the default value on creation for the opening_balance field.
	partymaster.DefaultOpeningBalance = partymasterDescOpeningBalance.Default.(float64)
	// partymasterDescCountry is the schema descriptor for country field.
	partymasterDescCountry := partymasterFields[17].Descriptor()
	// partymaster.DefaultCountry holds the default value on creation for the country field.
	partymaster.DefaultCountry = partymasterDescCountry.Default.(string)
	settingsMixin := schema.Settings{}.Mixin()
	settingsMixinFields0 := settingsMixin[0].Fields()
	_ = settingsMixinFields0
	settingsFields := schema.Settings{}.Fields()
	_ = settingsFields
	// settingsDescCreateTime is the schema descriptor for create_time field.
	settingsDescCreateTime := settingsMixinFields0[0].Descriptor()
	// settings.DefaultCreateTime holds the default value on creation for the create_time field.
	settings.DefaultCreateTime = settingsDescCreateTime.Default.(func() time.Time)
	// settingsDescUpdateTime is the schema descriptor for update_time field.
	settingsDescUpdateTime := settingsMixinFields0[1].Descriptor()
	// settings.DefaultUpdateTime holds the default value on creation for the update_time field.
	settings.DefaultUpdateTime = settingsDescUpdateTime.Default.(func() time.Time)
	// settings.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	settings.UpdateDefaultUpdateTime = settingsDescUpdateTime.UpdateDefault.(func() time.Time)
	// settingsDescKey is the schema descriptor for key field.
	settingsDescKey := settingsFields[1].Descriptor()
	// settings.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	settings.KeyValidator = func() func(string) error {
		validators := settingsDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// settingsDescValue is the schema descriptor for value field.
	settingsDescValue := settingsFields[2].Descriptor()
	// settings.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	settings.ValueValidator = settingsDescValue.Validators[0].(func(string) error)
	stateFields := schema.State{}.Fields()
	_ = stateFields
	// stateDescName is the schema descriptor for name field.
	stateDescName := stateFields[0].Descriptor()
	// state.NameValidator is a validator for the "name" field. It is called by the builders before save.
	state.NameValidator = func() func(string) error {
		validators := stateDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// stateDescCode is the schema descriptor for code field.
	stateDescCode := stateFields[1].Descriptor()
	// state.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	state.CodeValidator = stateDescCode.Validators[0].(func(string) error)
	// stateDescGstCode is the schema descriptor for gst_code field.
	stateDescGstCode := stateFields[2].Descriptor()
	// state.GstCodeValidator is a validator for the "gst_code" field. It is called by the builders before save.
	state.GstCodeValidator = stateDescGstCode.Validators[0].(func(string) error)
}
