// Code generated by ent, DO NOT EDIT.

package journal

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the journal type in the database.
	Label = "journal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldVoucherType holds the string denoting the voucher_type field in the database.
	FieldVoucherType = "voucher_type"
	// FieldVoucherNo holds the string denoting the voucher_no field in the database.
	FieldVoucherNo = "voucher_no"
	// FieldVoucherDate holds the string denoting the voucher_date field in the database.
	FieldVoucherDate = "voucher_date"
	// FieldReferenceNo holds the string denoting the reference_no field in the database.
	FieldReferenceNo = "reference_no"
	// FieldExternalRef holds the string denoting the external_ref field in the database.
	FieldExternalRef = "external_ref"
	// FieldJournalStatus holds the string denoting the journal_status field in the database.
	FieldJournalStatus = "journal_status"
	// FieldApprovedBy holds the string denoting the approved_by field in the database.
	FieldApprovedBy = "approved_by"
	// FieldFinancialYearID holds the string denoting the financial_year_id field in the database.
	FieldFinancialYearID = "financial_year_id"
	// FieldNarration holds the string denoting the narration field in the database.
	FieldNarration = "narration"
	// FieldSourceModule holds the string denoting the source_module field in the database.
	FieldSourceModule = "source_module"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldTotalDebit holds the string denoting the total_debit field in the database.
	FieldTotalDebit = "total_debit"
	// FieldTotalCredit holds the string denoting the total_credit field in the database.
	FieldTotalCredit = "total_credit"
	// EdgeLines holds the string denoting the lines edge name in mutations.
	EdgeLines = "lines"
	// Table holds the table name of the journal in the database.
	Table = "journals"
	// LinesTable is the table that holds the lines relation/edge.
	LinesTable = "journal_lines"
	// LinesInverseTable is the table name for the Journal_Line entity.
	// It exists in this package in order to avoid circular dependency with the "journal_line" package.
	LinesInverseTable = "journal_lines"
	// LinesColumn is the table column denoting the lines relation/edge.
	LinesColumn = "journal_id"
)

// Columns holds all SQL columns for journal fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDate,
	FieldVoucherType,
	FieldVoucherNo,
	FieldVoucherDate,
	FieldReferenceNo,
	FieldExternalRef,
	FieldJournalStatus,
	FieldApprovedBy,
	FieldFinancialYearID,
	FieldNarration,
	FieldSourceModule,
	FieldSourceType,
	FieldSourceID,
	FieldTotalDebit,
	FieldTotalCredit,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// VoucherTypeValidator is a validator for the "voucher_type" field. It is called by the builders before save.
	VoucherTypeValidator func(string) error
	// VoucherNoValidator is a validator for the "voucher_no" field. It is called by the builders before save.
	VoucherNoValidator func(string) error
	// DefaultTotalDebit holds the default value on creation for the "total_debit" field.
	DefaultTotalDebit float64
	// DefaultTotalCredit holds the default value on creation for the "total_credit" field.
	DefaultTotalCredit float64
)

// JournalStatus defines the type for the "journal_status" enum field.
type JournalStatus string

// JournalStatusDRAFT is the default value of the JournalStatus enum.
const DefaultJournalStatus = JournalStatusDRAFT

// JournalStatus values.
const (
	JournalStatusDRAFT     JournalStatus = "DRAFT"
	JournalStatusAPPROVED  JournalStatus = "APPROVED"
	JournalStatusPOSTED    JournalStatus = "POSTED"
	JournalStatusCANCELLED JournalStatus = "CANCELLED"
)

func (js JournalStatus) String() string {
	return string(js)
}

// JournalStatusValidator is a validator for the "journal_status" field enum values. It is called by the builders before save.
func JournalStatusValidator(js JournalStatus) error {
	switch js {
	case JournalStatusDRAFT, JournalStatusAPPROVED, JournalStatusPOSTED, JournalStatusCANCELLED:
		return nil
	default:
		return fmt.Errorf("journal: invalid enum value for journal_status field: %q", js)
	}
}

// OrderOption defines the ordering options for the Journal queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDate orders the results by the date field.
func ByDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDate, opts...).ToFunc()
}

// ByVoucherType orders the results by the voucher_type field.
func ByVoucherType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVoucherType, opts...).ToFunc()
}

// ByVoucherNo orders the results by the voucher_no field.
func ByVoucherNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVoucherNo, opts...).ToFunc()
}

// ByVoucherDate orders the results by the voucher_date field.
func ByVoucherDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVoucherDate, opts...).ToFunc()
}

// ByReferenceNo orders the results by the reference_no field.
func ByReferenceNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceNo, opts...).ToFunc()
}

// ByExternalRef orders the results by the external_ref field.
func ByExternalRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalRef, opts...).ToFunc()
}

// ByJournalStatus orders the results by the journal_status field.
func ByJournalStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJournalStatus, opts...).ToFunc()
}

// ByApprovedBy orders the results by the approved_by field.
func ByApprovedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedBy, opts...).ToFunc()
}

// ByFinancialYearID orders the results by the financial_year_id field.
func ByFinancialYearID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinancialYearID, opts...).ToFunc()
}

// ByNarration orders the results by the narration field.
func ByNarration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNarration, opts...).ToFunc()
}

// BySourceModule orders the results by the source_module field.
func BySourceModule(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceModule, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// ByTotalDebit orders the results by the total_debit field.
func ByTotalDebit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalDebit, opts...).ToFunc()
}

// ByTotalCredit orders the results by the total_credit field.
func ByTotalCredit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCredit, opts...).ToFunc()
}

// ByLinesCount orders the results by lines count.
func ByLinesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLinesStep(), opts...)
	}
}

// ByLines orders the results by lines terms.
func ByLines(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLinesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newLinesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LinesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LinesTable, LinesColumn),
	)
}
