// Code generated by ent, DO NOT EDIT.

package journal_line

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/subhasundardass/retui/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldUpdateTime, v))
}

// JournalID applies equality check predicate on the "journal_id" field. It's identical to JournalIDEQ.
func JournalID(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldJournalID, v))
}

// LedgerID applies equality check predicate on the "ledger_id" field. It's identical to LedgerIDEQ.
func LedgerID(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldLedgerID, v))
}

// Debit applies equality check predicate on the "debit" field. It's identical to DebitEQ.
func Debit(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldDebit, v))
}

// Credit applies equality check predicate on the "credit" field. It's identical to CreditEQ.
func Credit(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldCredit, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldDescription, v))
}

// ReferenceType applies equality check predicate on the "reference_type" field. It's identical to ReferenceTypeEQ.
func ReferenceType(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldReferenceType, v))
}

// ReferenceID applies equality check predicate on the "reference_id" field. It's identical to ReferenceIDEQ.
func ReferenceID(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldReferenceID, v))
}

// LineNo applies equality check predicate on the "line_no" field. It's identical to LineNoEQ.
func LineNo(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldLineNo, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldUpdateTime, v))
}

// JournalIDEQ applies the EQ predicate on the "journal_id" field.
func JournalIDEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldJournalID, v))
}

// JournalIDNEQ applies the NEQ predicate on the "journal_id" field.
func JournalIDNEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldJournalID, v))
}

// JournalIDIn applies the In predicate on the "journal_id" field.
func JournalIDIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldJournalID, vs...))
}

// JournalIDNotIn applies the NotIn predicate on the "journal_id" field.
func JournalIDNotIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldJournalID, vs...))
}

// LedgerIDEQ applies the EQ predicate on the "ledger_id" field.
func LedgerIDEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldLedgerID, v))
}

// LedgerIDNEQ applies the NEQ predicate on the "ledger_id" field.
func LedgerIDNEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldLedgerID, v))
}

// LedgerIDIn applies the In predicate on the "ledger_id" field.
func LedgerIDIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldLedgerID, vs...))
}

// LedgerIDNotIn applies the NotIn predicate on the "ledger_id" field.
func LedgerIDNotIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldLedgerID, vs...))
}

// DebitEQ applies the EQ predicate on the "debit" field.
func DebitEQ(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldDebit, v))
}

// DebitNEQ applies the NEQ predicate on the "debit" field.
func DebitNEQ(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldDebit, v))
}

// DebitIn applies the In predicate on the "debit" field.
func DebitIn(vs ...float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldDebit, vs...))
}

// DebitNotIn applies the NotIn predicate on the "debit" field.
func DebitNotIn(vs ...float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldDebit, vs...))
}

// DebitGT applies the GT predicate on the "debit" field.
func DebitGT(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldDebit, v))
}

// DebitGTE applies the GTE predicate on the "debit" field.
func DebitGTE(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldDebit, v))
}

// DebitLT applies the LT predicate on the "debit" field.
func DebitLT(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldDebit, v))
}

// DebitLTE applies the LTE predicate on the "debit" field.
func DebitLTE(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldDebit, v))
}

// CreditEQ applies the EQ predicate on the "credit" field.
func CreditEQ(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldCredit, v))
}

// CreditNEQ applies the NEQ predicate on the "credit" field.
func CreditNEQ(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldCredit, v))
}

// CreditIn applies the In predicate on the "credit" field.
func CreditIn(vs ...float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldCredit, vs...))
}

// CreditNotIn applies the NotIn predicate on the "credit" field.
func CreditNotIn(vs ...float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldCredit, vs...))
}

// CreditGT applies the GT predicate on the "credit" field.
func CreditGT(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldCredit, v))
}

// CreditGTE applies the GTE predicate on the "credit" field.
func CreditGTE(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldCredit, v))
}

// CreditLT applies the LT predicate on the "credit" field.
func CreditLT(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldCredit, v))
}

// CreditLTE applies the LTE predicate on the "credit" field.
func CreditLTE(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldCredit, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldContainsFold(FieldDescription, v))
}

// ReferenceTypeEQ applies the EQ predicate on the "reference_type" field.
func ReferenceTypeEQ(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldReferenceType, v))
}

// ReferenceTypeNEQ applies the NEQ predicate on the "reference_type" field.
func ReferenceTypeNEQ(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldReferenceType, v))
}

// ReferenceTypeIn applies the In predicate on the "reference_type" field.
func ReferenceTypeIn(vs ...string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldReferenceType, vs...))
}

// ReferenceTypeNotIn applies the NotIn predicate on the "reference_type" field.
func ReferenceTypeNotIn(vs ...string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldReferenceType, vs...))
}

// ReferenceTypeGT applies the GT predicate on the "reference_type" field.
func ReferenceTypeGT(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldReferenceType, v))
}

// ReferenceTypeGTE applies the GTE predicate on the "reference_type" field.
func ReferenceTypeGTE(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldReferenceType, v))
}

// ReferenceTypeLT applies the LT predicate on the "reference_type" field.
func ReferenceTypeLT(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldReferenceType, v))
}

// ReferenceTypeLTE applies the LTE predicate on the "reference_type" field.
func ReferenceTypeLTE(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldReferenceType, v))
}

// ReferenceTypeContains applies the Contains predicate on the "reference_type" field.
func ReferenceTypeContains(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldContains(FieldReferenceType, v))
}

// ReferenceTypeHasPrefix applies the HasPrefix predicate on the "reference_type" field.
func ReferenceTypeHasPrefix(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldHasPrefix(FieldReferenceType, v))
}

// ReferenceTypeHasSuffix applies the HasSuffix predicate on the "reference_type" field.
func ReferenceTypeHasSuffix(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldHasSuffix(FieldReferenceType, v))
}

// ReferenceTypeIsNil applies the IsNil predicate on the "reference_type" field.
func ReferenceTypeIsNil() predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIsNull(FieldReferenceType))
}

// ReferenceTypeNotNil applies the NotNil predicate on the "reference_type" field.
func ReferenceTypeNotNil() predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotNull(FieldReferenceType))
}

// ReferenceTypeEqualFold applies the EqualFold predicate on the "reference_type" field.
func ReferenceTypeEqualFold(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEqualFold(FieldReferenceType, v))
}

// ReferenceTypeContainsFold applies the ContainsFold predicate on the "reference_type" field.
func ReferenceTypeContainsFold(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldContainsFold(FieldReferenceType, v))
}

// ReferenceIDEQ applies the EQ predicate on the "reference_id" field.
func ReferenceIDEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldReferenceID, v))
}

// ReferenceIDNEQ applies the NEQ predicate on the "reference_id" field.
func ReferenceIDNEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldReferenceID, v))
}

// ReferenceIDIn applies the In predicate on the "reference_id" field.
func ReferenceIDIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldReferenceID, vs...))
}

// ReferenceIDNotIn applies the NotIn predicate on the "reference_id" field.
func ReferenceIDNotIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldReferenceID, vs...))
}

// ReferenceIDGT applies the GT predicate on the "reference_id" field.
func ReferenceIDGT(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldReferenceID, v))
}

// ReferenceIDGTE applies the GTE predicate on the "reference_id" field.
func ReferenceIDGTE(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldReferenceID, v))
}

// ReferenceIDLT applies the LT predicate on the "reference_id" field.
func ReferenceIDLT(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldReferenceID, v))
}

// ReferenceIDLTE applies the LTE predicate on the "reference_id" field.
func ReferenceIDLTE(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldReferenceID, v))
}

// ReferenceIDIsNil applies the IsNil predicate on the "reference_id" field.
func ReferenceIDIsNil() predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIsNull(FieldReferenceID))
}

// ReferenceIDNotNil applies the NotNil predicate on the "reference_id" field.
func ReferenceIDNotNil() predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotNull(FieldReferenceID))
}

// LineNoEQ applies the EQ predicate on the "line_no" field.
func LineNoEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldLineNo, v))
}

// LineNoNEQ applies the NEQ predicate on the "line_no" field.
func LineNoNEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldLineNo, v))
}

// LineNoIn applies the In predicate on the "line_no" field.
func LineNoIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldLineNo, vs...))
}

// LineNoNotIn applies the NotIn predicate on the "line_no" field.
func LineNoNotIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldLineNo, vs...))
}

// LineNoGT applies the GT predicate on the "line_no" field.
func LineNoGT(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldLineNo, v))
}

// LineNoGTE applies the GTE predicate on the "line_no" field.
func LineNoGTE(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldLineNo, v))
}

// LineNoLT applies the LT predicate on the "line_no" field.
func LineNoLT(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldLineNo, v))
}

// LineNoLTE applies the LTE predicate on the "line_no" field.
func LineNoLTE(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldLineNo, v))
}

// HasJournal applies the HasEdge predicate on the "journal" edge.
func HasJournal() predicate.Journal_Line {
	return predicate.Journal_Line(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, JournalTable, JournalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJournalWith applies the HasEdge predicate on the "journal" edge with a given conditions (other predicates).
func HasJournalWith(preds ...predicate.Journal) predicate.Journal_Line {
	return predicate.Journal_Line(func(s *sql.Selector) {
		step := newJournalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLedger applies the HasEdge predicate on the "ledger" edge.
func HasLedger() predicate.Journal_Line {
	return predicate.Journal_Line(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LedgerTable, LedgerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerWith applies the HasEdge predicate on the "ledger" edge with a given conditions (other predicates).
func HasLedgerWith(preds ...predicate.Ledger) predicate.Journal_Line {
	return predicate.Journal_Line(func(s *sql.Selector) {
		step := newLedgerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Journal_Line) predicate.Journal_Line {
	return predicate.Journal_Line(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Journal_Line) predicate.Journal_Line {
	return predicate.Journal_Line(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Journal_Line) predicate.Journal_Line {
	return predicate.Journal_Line(sql.NotPredicates(p))
}
