// Code generated by ent, DO NOT EDIT.

package ledger

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ledger type in the database.
	Label = "ledger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAlias holds the string denoting the alias field in the database.
	FieldAlias = "alias"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldPartyType holds the string denoting the party_type field in the database.
	FieldPartyType = "party_type"
	// FieldAddressLine1 holds the string denoting the address_line1 field in the database.
	FieldAddressLine1 = "address_line1"
	// FieldAddressLine2 holds the string denoting the address_line2 field in the database.
	FieldAddressLine2 = "address_line2"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldPincode holds the string denoting the pincode field in the database.
	FieldPincode = "pincode"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldMobile holds the string denoting the mobile field in the database.
	FieldMobile = "mobile"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldContactPerson holds the string denoting the contact_person field in the database.
	FieldContactPerson = "contact_person"
	// FieldGstRegistrationType holds the string denoting the gst_registration_type field in the database.
	FieldGstRegistrationType = "gst_registration_type"
	// FieldGstin holds the string denoting the gstin field in the database.
	FieldGstin = "gstin"
	// FieldPan holds the string denoting the pan field in the database.
	FieldPan = "pan"
	// FieldBankName holds the string denoting the bank_name field in the database.
	FieldBankName = "bank_name"
	// FieldBankAccountNo holds the string denoting the bank_account_no field in the database.
	FieldBankAccountNo = "bank_account_no"
	// FieldBankIfsc holds the string denoting the bank_ifsc field in the database.
	FieldBankIfsc = "bank_ifsc"
	// FieldBankBranch holds the string denoting the bank_branch field in the database.
	FieldBankBranch = "bank_branch"
	// FieldIsSystem holds the string denoting the is_system field in the database.
	FieldIsSystem = "is_system"
	// FieldIsParty holds the string denoting the is_party field in the database.
	FieldIsParty = "is_party"
	// FieldIsBank holds the string denoting the is_bank field in the database.
	FieldIsBank = "is_bank"
	// FieldIsCash holds the string denoting the is_cash field in the database.
	FieldIsCash = "is_cash"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeJournalLines holds the string denoting the journal_lines edge name in mutations.
	EdgeJournalLines = "journal_lines"
	// Table holds the table name of the ledger in the database.
	Table = "ledgers"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "ledgers"
	// GroupInverseTable is the table name for the Ledger_Group entity.
	// It exists in this package in order to avoid circular dependency with the "ledger_group" package.
	GroupInverseTable = "ledger_groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// JournalLinesTable is the table that holds the journal_lines relation/edge.
	JournalLinesTable = "journal_lines"
	// JournalLinesInverseTable is the table name for the Journal_Line entity.
	// It exists in this package in order to avoid circular dependency with the "journal_line" package.
	JournalLinesInverseTable = "journal_lines"
	// JournalLinesColumn is the table column denoting the journal_lines relation/edge.
	JournalLinesColumn = "ledger_id"
)

// Columns holds all SQL columns for ledger fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldGroupID,
	FieldCode,
	FieldName,
	FieldAlias,
	FieldDescription,
	FieldBalance,
	FieldPartyType,
	FieldAddressLine1,
	FieldAddressLine2,
	FieldCity,
	FieldState,
	FieldCountry,
	FieldPincode,
	FieldPhone,
	FieldMobile,
	FieldEmail,
	FieldContactPerson,
	FieldGstRegistrationType,
	FieldGstin,
	FieldPan,
	FieldBankName,
	FieldBankAccountNo,
	FieldBankIfsc,
	FieldBankBranch,
	FieldIsSystem,
	FieldIsParty,
	FieldIsBank,
	FieldIsCash,
	FieldIsActive,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "ledgers"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"ledger_group_ledgers",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultAlias holds the default value on creation for the "alias" field.
	DefaultAlias string
	// AliasValidator is a validator for the "alias" field. It is called by the builders before save.
	AliasValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultBalance holds the default value on creation for the "balance" field.
	DefaultBalance float64
	// DefaultAddressLine1 holds the default value on creation for the "address_line1" field.
	DefaultAddressLine1 string
	// AddressLine1Validator is a validator for the "address_line1" field. It is called by the builders before save.
	AddressLine1Validator func(string) error
	// DefaultAddressLine2 holds the default value on creation for the "address_line2" field.
	DefaultAddressLine2 string
	// AddressLine2Validator is a validator for the "address_line2" field. It is called by the builders before save.
	AddressLine2Validator func(string) error
	// DefaultCity holds the default value on creation for the "city" field.
	DefaultCity string
	// CityValidator is a validator for the "city" field. It is called by the builders before save.
	CityValidator func(string) error
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState string
	// StateValidator is a validator for the "state" field. It is called by the builders before save.
	StateValidator func(string) error
	// DefaultCountry holds the default value on creation for the "country" field.
	DefaultCountry string
	// CountryValidator is a validator for the "country" field. It is called by the builders before save.
	CountryValidator func(string) error
	// DefaultPincode holds the default value on creation for the "pincode" field.
	DefaultPincode string
	// PincodeValidator is a validator for the "pincode" field. It is called by the builders before save.
	PincodeValidator func(string) error
	// DefaultPhone holds the default value on creation for the "phone" field.
	DefaultPhone string
	// PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	PhoneValidator func(string) error
	// DefaultMobile holds the default value on creation for the "mobile" field.
	DefaultMobile string
	// MobileValidator is a validator for the "mobile" field. It is called by the builders before save.
	MobileValidator func(string) error
	// DefaultEmail holds the default value on creation for the "email" field.
	DefaultEmail string
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultContactPerson holds the default value on creation for the "contact_person" field.
	DefaultContactPerson string
	// ContactPersonValidator is a validator for the "contact_person" field. It is called by the builders before save.
	ContactPersonValidator func(string) error
	// DefaultGstin holds the default value on creation for the "gstin" field.
	DefaultGstin string
	// GstinValidator is a validator for the "gstin" field. It is called by the builders before save.
	GstinValidator func(string) error
	// DefaultPan holds the default value on creation for the "pan" field.
	DefaultPan string
	// PanValidator is a validator for the "pan" field. It is called by the builders before save.
	PanValidator func(string) error
	// DefaultBankName holds the default value on creation for the "bank_name" field.
	DefaultBankName string
	// BankNameValidator is a validator for the "bank_name" field. It is called by the builders before save.
	BankNameValidator func(string) error
	// DefaultBankAccountNo holds the default value on creation for the "bank_account_no" field.
	DefaultBankAccountNo string
	// BankAccountNoValidator is a validator for the "bank_account_no" field. It is called by the builders before save.
	BankAccountNoValidator func(string) error
	// DefaultBankIfsc holds the default value on creation for the "bank_ifsc" field.
	DefaultBankIfsc string
	// BankIfscValidator is a validator for the "bank_ifsc" field. It is called by the builders before save.
	BankIfscValidator func(string) error
	// DefaultBankBranch holds the default value on creation for the "bank_branch" field.
	DefaultBankBranch string
	// BankBranchValidator is a validator for the "bank_branch" field. It is called by the builders before save.
	BankBranchValidator func(string) error
	// DefaultIsSystem holds the default value on creation for the "is_system" field.
	DefaultIsSystem bool
	// DefaultIsParty holds the default value on creation for the "is_party" field.
	DefaultIsParty bool
	// DefaultIsBank holds the default value on creation for the "is_bank" field.
	DefaultIsBank bool
	// DefaultIsCash holds the default value on creation for the "is_cash" field.
	DefaultIsCash bool
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
)

// PartyType defines the type for the "party_type" enum field.
type PartyType string

// PartyTypeINTERNAL is the default value of the PartyType enum.
const DefaultPartyType = PartyTypeINTERNAL

// PartyType values.
const (
	PartyTypeCUSTOMER PartyType = "CUSTOMER"
	PartyTypeSUPPLIER PartyType = "SUPPLIER"
	PartyTypeBOTH     PartyType = "BOTH"
	PartyTypeINTERNAL PartyType = "INTERNAL"
)

func (pt PartyType) String() string {
	return string(pt)
}

// PartyTypeValidator is a validator for the "party_type" field enum values. It is called by the builders before save.
func PartyTypeValidator(pt PartyType) error {
	switch pt {
	case PartyTypeCUSTOMER, PartyTypeSUPPLIER, PartyTypeBOTH, PartyTypeINTERNAL:
		return nil
	default:
		return fmt.Errorf("ledger: invalid enum value for party_type field: %q", pt)
	}
}

// GstRegistrationType defines the type for the "gst_registration_type" enum field.
type GstRegistrationType string

// GstRegistrationTypeUNREGISTERED is the default value of the GstRegistrationType enum.
const DefaultGstRegistrationType = GstRegistrationTypeUNREGISTERED

// GstRegistrationType values.
const (
	GstRegistrationTypeREGULAR      GstRegistrationType = "REGULAR"
	GstRegistrationTypeCOMPOSITION  GstRegistrationType = "COMPOSITION"
	GstRegistrationTypeUNREGISTERED GstRegistrationType = "UNREGISTERED"
	GstRegistrationTypeCONSUMER     GstRegistrationType = "CONSUMER"
	GstRegistrationTypeSEZ          GstRegistrationType = "SEZ"
	GstRegistrationTypeOVERSEAS     GstRegistrationType = "OVERSEAS"
)

func (grt GstRegistrationType) String() string {
	return string(grt)
}

// GstRegistrationTypeValidator is a validator for the "gst_registration_type" field enum values. It is called by the builders before save.
func GstRegistrationTypeValidator(grt GstRegistrationType) error {
	switch grt {
	case GstRegistrationTypeREGULAR, GstRegistrationTypeCOMPOSITION, GstRegistrationTypeUNREGISTERED, GstRegistrationTypeCONSUMER, GstRegistrationTypeSEZ, GstRegistrationTypeOVERSEAS:
		return nil
	default:
		return fmt.Errorf("ledger: invalid enum value for gst_registration_type field: %q", grt)
	}
}

// OrderOption defines the ordering options for the Ledger queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAlias orders the results by the alias field.
func ByAlias(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlias, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByBalance orders the results by the balance field.
func ByBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalance, opts...).ToFunc()
}

// ByPartyType orders the results by the party_type field.
func ByPartyType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPartyType, opts...).ToFunc()
}

// ByAddressLine1 orders the results by the address_line1 field.
func ByAddressLine1(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddressLine1, opts...).ToFunc()
}

// ByAddressLine2 orders the results by the address_line2 field.
func ByAddressLine2(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddressLine2, opts...).ToFunc()
}

// ByCity orders the results by the city field.
func ByCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCity, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByPincode orders the results by the pincode field.
func ByPincode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPincode, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByMobile orders the results by the mobile field.
func ByMobile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMobile, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByContactPerson orders the results by the contact_person field.
func ByContactPerson(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactPerson, opts...).ToFunc()
}

// ByGstRegistrationType orders the results by the gst_registration_type field.
func ByGstRegistrationType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGstRegistrationType, opts...).ToFunc()
}

// ByGstin orders the results by the gstin field.
func ByGstin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGstin, opts...).ToFunc()
}

// ByPan orders the results by the pan field.
func ByPan(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPan, opts...).ToFunc()
}

// ByBankName orders the results by the bank_name field.
func ByBankName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBankName, opts...).ToFunc()
}

// ByBankAccountNo orders the results by the bank_account_no field.
func ByBankAccountNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBankAccountNo, opts...).ToFunc()
}

// ByBankIfsc orders the results by the bank_ifsc field.
func ByBankIfsc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBankIfsc, opts...).ToFunc()
}

// ByBankBranch orders the results by the bank_branch field.
func ByBankBranch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBankBranch, opts...).ToFunc()
}

// ByIsSystem orders the results by the is_system field.
func ByIsSystem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSystem, opts...).ToFunc()
}

// ByIsParty orders the results by the is_party field.
func ByIsParty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsParty, opts...).ToFunc()
}

// ByIsBank orders the results by the is_bank field.
func ByIsBank(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsBank, opts...).ToFunc()
}

// ByIsCash orders the results by the is_cash field.
func ByIsCash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCash, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByJournalLinesCount orders the results by journal_lines count.
func ByJournalLinesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newJournalLinesStep(), opts...)
	}
}

// ByJournalLines orders the results by journal_lines terms.
func ByJournalLines(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJournalLinesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
	)
}
func newJournalLinesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JournalLinesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, JournalLinesTable, JournalLinesColumn),
	)
}
