// Code generated by ent, DO NOT EDIT.

package ledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ledger type in the database.
	Label = "ledger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAlias holds the string denoting the alias field in the database.
	FieldAlias = "alias"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldOpeningBalance holds the string denoting the opening_balance field in the database.
	FieldOpeningBalance = "opening_balance"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldIsSystem holds the string denoting the is_system field in the database.
	FieldIsSystem = "is_system"
	// FieldIsParty holds the string denoting the is_party field in the database.
	FieldIsParty = "is_party"
	// FieldIsBank holds the string denoting the is_bank field in the database.
	FieldIsBank = "is_bank"
	// FieldIsCash holds the string denoting the is_cash field in the database.
	FieldIsCash = "is_cash"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeParty holds the string denoting the party edge name in mutations.
	EdgeParty = "party"
	// EdgeJournalLines holds the string denoting the journal_lines edge name in mutations.
	EdgeJournalLines = "journal_lines"
	// Table holds the table name of the ledger in the database.
	Table = "ledgers"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "ledgers"
	// GroupInverseTable is the table name for the Ledger_Group entity.
	// It exists in this package in order to avoid circular dependency with the "ledger_group" package.
	GroupInverseTable = "ledger_groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// PartyTable is the table that holds the party relation/edge.
	PartyTable = "party_master"
	// PartyInverseTable is the table name for the PartyMaster entity.
	// It exists in this package in order to avoid circular dependency with the "partymaster" package.
	PartyInverseTable = "party_master"
	// PartyColumn is the table column denoting the party relation/edge.
	PartyColumn = "ledger_id"
	// JournalLinesTable is the table that holds the journal_lines relation/edge.
	JournalLinesTable = "journal_lines"
	// JournalLinesInverseTable is the table name for the Journal_Line entity.
	// It exists in this package in order to avoid circular dependency with the "journal_line" package.
	JournalLinesInverseTable = "journal_lines"
	// JournalLinesColumn is the table column denoting the journal_lines relation/edge.
	JournalLinesColumn = "ledger_id"
)

// Columns holds all SQL columns for ledger fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldGroupID,
	FieldCode,
	FieldName,
	FieldAlias,
	FieldDescription,
	FieldOpeningBalance,
	FieldBalance,
	FieldIsSystem,
	FieldIsParty,
	FieldIsBank,
	FieldIsCash,
	FieldIsActive,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "ledgers"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"ledger_group_ledgers",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultAlias holds the default value on creation for the "alias" field.
	DefaultAlias string
	// AliasValidator is a validator for the "alias" field. It is called by the builders before save.
	AliasValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultOpeningBalance holds the default value on creation for the "opening_balance" field.
	DefaultOpeningBalance float64
	// DefaultBalance holds the default value on creation for the "balance" field.
	DefaultBalance float64
	// DefaultIsSystem holds the default value on creation for the "is_system" field.
	DefaultIsSystem bool
	// DefaultIsParty holds the default value on creation for the "is_party" field.
	DefaultIsParty bool
	// DefaultIsBank holds the default value on creation for the "is_bank" field.
	DefaultIsBank bool
	// DefaultIsCash holds the default value on creation for the "is_cash" field.
	DefaultIsCash bool
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
)

// OrderOption defines the ordering options for the Ledger queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAlias orders the results by the alias field.
func ByAlias(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlias, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByOpeningBalance orders the results by the opening_balance field.
func ByOpeningBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpeningBalance, opts...).ToFunc()
}

// ByBalance orders the results by the balance field.
func ByBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalance, opts...).ToFunc()
}

// ByIsSystem orders the results by the is_system field.
func ByIsSystem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSystem, opts...).ToFunc()
}

// ByIsParty orders the results by the is_party field.
func ByIsParty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsParty, opts...).ToFunc()
}

// ByIsBank orders the results by the is_bank field.
func ByIsBank(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsBank, opts...).ToFunc()
}

// ByIsCash orders the results by the is_cash field.
func ByIsCash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCash, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByPartyField orders the results by party field.
func ByPartyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPartyStep(), sql.OrderByField(field, opts...))
	}
}

// ByJournalLinesCount orders the results by journal_lines count.
func ByJournalLinesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newJournalLinesStep(), opts...)
	}
}

// ByJournalLines orders the results by journal_lines terms.
func ByJournalLines(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJournalLinesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
	)
}
func newPartyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PartyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, PartyTable, PartyColumn),
	)
}
func newJournalLinesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JournalLinesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, JournalLinesTable, JournalLinesColumn),
	)
}
