// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Country is the predicate function for country builders.
type Country func(*sql.Selector)

// Journal is the predicate function for journal builders.
type Journal func(*sql.Selector)

// Journal_Line is the predicate function for journal_line builders.
type Journal_Line func(*sql.Selector)

// Ledger is the predicate function for ledger builders.
type Ledger func(*sql.Selector)

// Ledger_Group is the predicate function for ledger_group builders.
type Ledger_Group func(*sql.Selector)

// PartyMaster is the predicate function for partymaster builders.
type PartyMaster func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)

// State is the predicate function for state builders.
type State func(*sql.Selector)
